import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const cyberAuthorities = [
  {
    id: 'ca-pk-001',
    name: 'Federal Investigation Agency (FIA) - Cyber Crime Wing',
    country: 'Pakistan',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://www.fia.gov.pk',
    phone: '+92-51-9269111',
    email: 'info@fia.gov.pk',
    address: 'FIA Headquarters, G-5/2, Islamabad, Pakistan',
    reportingUrl: 'https://complaint.fia.gov.pk',
    description: 'Pakistan\'s primary federal law enforcement agency responsible for investigating cybercrime including online fraud, identity theft, data breaches, and electronic financial crimes. The Cyber Crime Wing handles complaints related to online harassment, defamation, and unauthorized access to computer systems under the Prevention of Electronic Crimes Act (PECA) 2016.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-pk-002',
    name: 'Pakistan Telecommunication Authority (PTA)',
    country: 'Pakistan',
    type: 'government',
    category: 'telecom_regulator',
    website: 'https://www.pta.gov.pk',
    phone: '0800-55055',
    email: 'complaint@pta.gov.pk',
    address: 'PTA Headquarters, Sector F-5/1, Islamabad, Pakistan',
    reportingUrl: 'https://complaint.pta.gov.pk/RegisterComplaint.aspx',
    description: 'Pakistan\'s telecom regulatory authority responsible for blocking fraudulent SIM cards, scam websites, and fake telecom operations. PTA works with ISPs and mobile operators to combat spam messages, fraudulent calls, and phishing attempts via telecommunications.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-pk-003',
    name: 'Pakistan Cyber Crime Wing (National Response Centre)',
    country: 'Pakistan',
    type: 'government',
    category: 'cyber_cell',
    website: 'https://www.nccia.gov.pk',
    phone: '1991',
    email: 'cybercrime@nccia.gov.pk',
    address: 'National Response Centre for Cyber Crimes, FIA HQ, Islamabad',
    reportingUrl: 'https://complaint.nccia.gov.pk',
    description: 'Dedicated cyber crime reporting and response center under FIA. Operates the national helpline 1991 for immediate reporting of cyber crimes. Handles cases of online fraud, child exploitation, cyber terrorism, and electronic forgery.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-us-001',
    name: 'Federal Trade Commission (FTC)',
    country: 'United States',
    type: 'government',
    category: 'consumer_protection',
    website: 'https://www.ftc.gov',
    phone: '+1-877-382-4357',
    email: null,
    address: '600 Pennsylvania Avenue NW, Washington, DC 20580, USA',
    reportingUrl: 'https://reportfraud.ftc.gov',
    description: 'The primary U.S. federal agency for consumer protection. Handles complaints about fraud, scams, deceptive business practices, identity theft, and unfair business practices. Provides consumer education and enforcement against fraudulent businesses.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-us-002',
    name: 'FBI Internet Crime Complaint Center (IC3)',
    country: 'United States',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://www.ic3.gov',
    phone: null,
    email: null,
    address: 'FBI Headquarters, 935 Pennsylvania Avenue NW, Washington, DC 20535, USA',
    reportingUrl: 'https://www.ic3.gov/Home/ComplaintChoice',
    description: 'The FBI\'s centralized hub for receiving and analyzing cyber crime complaints from the public and private sectors. IC3 investigates and shares information about internet crime including business email compromise, ransomware, tech support fraud, and online investment fraud.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-us-003',
    name: 'Cybersecurity and Infrastructure Security Agency (CISA)',
    country: 'United States',
    type: 'government',
    category: 'cyber_cell',
    website: 'https://www.cisa.gov',
    phone: '+1-888-282-0870',
    email: 'vulnerability@cisa.gov',
    address: 'CISA Headquarters, 355 E Street SW, Washington, DC 20024, USA',
    reportingUrl: 'https://www.cisa.gov/report',
    description: 'U.S. federal agency responsible for protecting critical infrastructure from cyber threats. Provides cybersecurity resources, vulnerability alerts, incident reporting, and guidance for organizations and individuals on cyber defense.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-uk-001',
    name: 'Action Fraud',
    country: 'United Kingdom',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://www.actionfraud.police.uk',
    phone: '+44-300-123-2040',
    email: null,
    address: 'Action Fraud, PO Box 8082, London EC2A 4LP, UK',
    reportingUrl: 'https://www.actionfraud.police.uk/reporting-fraud-and-cyber-crime',
    description: 'The UK\'s national reporting centre for fraud and cybercrime. Run by the City of London Police in partnership with the National Fraud Intelligence Bureau. All fraud and cybercrime reports are analyzed and directed to the appropriate law enforcement agencies for investigation.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-uk-002',
    name: 'National Crime Agency (NCA) - Cyber Crime Unit',
    country: 'United Kingdom',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://www.nationalcrimeagency.gov.uk',
    phone: null,
    email: null,
    address: 'National Crime Agency, 99 High Holborn, London WC1V 6JX, UK',
    reportingUrl: 'https://www.actionfraud.police.uk/reporting-fraud-and-cyber-crime',
    description: 'The UK\'s lead agency against serious and organised crime. The Cyber Crime Unit tackles the most serious cyber threats including ransomware, DDoS attacks, and state-sponsored cyber operations. Works closely with international partners.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-in-001',
    name: 'Cyber Crime Cell',
    country: 'India',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://cybercrime.gov.in',
    phone: '1930',
    email: null,
    address: 'National Cyber Crime Reporting Portal, India',
    reportingUrl: 'https://cybercrime.gov.in',
    description: 'India\'s national portal for reporting cyber crimes including online fraud, identity theft, cyberstalking, and financial fraud. The portal allows citizens to report complaints online and tracks them through investigation. Operated by the Ministry of Home Affairs.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-in-002',
    name: 'Indian Computer Emergency Response Team (CERT-In)',
    country: 'India',
    type: 'government',
    category: 'cyber_cell',
    website: 'https://www.cert-in.org.in',
    phone: '+91-11-24368572',
    email: 'incident@cert-in.org.in',
    address: 'CERT-In, CDAC Building, 6th Floor, A-Wing, Old Mumba Highway, Pune 411037, India',
    reportingUrl: 'https://www.cert-in.org.in/reportincident',
    description: 'India\'s national nodal agency for responding to cybersecurity incidents. CERT-In collects, analyses, and disseminates cyber threat intelligence, coordinates incident response activities, and issues advisories on cybersecurity vulnerabilities and best practices.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-ae-001',
    name: 'Dubai Police - Cyber Crime Division',
    country: 'United Arab Emirates',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://www.dubaipolice.gov.ae',
    phone: '901',
    email: null,
    address: 'Dubai Police HQ, Al Tawar, Dubai, UAE',
    reportingUrl: 'https://www.dubaipolice.gov.ae/wps/portal/home/services/6-service-detail/6.5-reportcybercrime',
    description: 'Dubai Police Cyber Crime Division handles all digital crime investigations in the emirate of Dubai. Provides online reporting for internet fraud, social media crimes, online blackmail, electronic fraud, and hacking incidents.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-ae-002',
    name: 'Abu Dhabi Police - Cyber Crime Division',
    country: 'United Arab Emirates',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://www.adpolice.gov.ae',
    phone: '999',
    email: null,
    address: 'Abu Dhabi Police HQ, Abu Dhabi, UAE',
    reportingUrl: 'https://www.adpolice.gov.ae/en/Services/Pages/Cyber-Crime.aspx',
    description: 'Abu Dhabi Police Cyber Crime Division investigates and responds to cyber crimes in the Abu Dhabi emirate. Offers electronic reporting services for online fraud, identity theft, and digital financial crimes.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-de-001',
    name: 'Federal Office for Information Security (BSI)',
    country: 'Germany',
    type: 'government',
    category: 'cyber_cell',
    website: 'https://www.bsi.bund.de',
    phone: '+49-228-99-9582-5959',
    email: 'info@bsi.bund.de',
    address: 'Godesberger Allee 188-196, 53175 Bonn, Germany',
    reportingUrl: 'https://www.bsi.bund.de/SiteGlobals/EN/Contact/ReportVulnerability/reportVulnerability_Node.html',
    description: 'Germany\'s federal cybersecurity agency responsible for protecting IT infrastructure, conducting cybersecurity research, and issuing security advisories. Provides resources and guidance for citizens and organizations on cyber threats and defense.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-de-002',
    name: 'Bundeskriminalamt (BKA) - Cyber Crime Division',
    country: 'Germany',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://www.bka.de',
    phone: '+49-611-55-0',
    email: null,
    address: 'Dunantstraße 4, 65193 Wiesbaden, Germany',
    reportingUrl: 'https://www.bka.de/EN/CurrentInformation/Cybercrime/cybercrime_node.html',
    description: 'Germany\'s Federal Criminal Police Office cyber crime unit investigates serious cyber offenses including online fraud, ransomware attacks, and cyber-enabled organized crime. Coordinates with Europol and Interpol on international cyber crime cases.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-ca-001',
    name: 'Canadian Anti-Fraud Centre (CAFC)',
    country: 'Canada',
    type: 'government',
    category: 'consumer_protection',
    website: 'https://www.antifraudcentre-centreantifraude.ca',
    phone: '+1-888-495-8501',
    email: null,
    address: 'Canadian Anti-Fraud Centre, 701 Cyclops Street, Pembroke, ON K8A 5Y7, Canada',
    reportingUrl: 'https://www.antifraudcentre-centreantifraude.ca/scams-fraudes/report-declarer-eng.aspx',
    description: 'Canada\'s central agency for reporting and tracking fraud and cybercrime. Collects information on fraud attempts, provides consumer education, and supports law enforcement investigations. Maintains a database of reported scams used for intelligence analysis.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-au-001',
    name: 'Australian Cyber Security Centre (ACSC)',
    country: 'Australia',
    type: 'government',
    category: 'cyber_cell',
    website: 'https://www.cyber.gov.au',
    phone: '1300 292 371',
    email: null,
    address: 'Australian Cyber Security Centre, GPO Box 3208, Canberra ACT 2601, Australia',
    reportingUrl: 'https://www.cyber.gov.au/report-and-recover/report',
    description: 'Australia\'s whole-of-government cybersecurity hub. Provides resources for protecting against cyber threats, coordinates national cyber incident response, and supports critical infrastructure protection. Citizens can report cybercrime through the ACSC.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-au-002',
    name: 'Scamwatch (ACCC)',
    country: 'Australia',
    type: 'government',
    category: 'consumer_protection',
    website: 'https://www.scamwatch.gov.au',
    phone: null,
    email: null,
    address: 'Scamwatch, Australian Competition and Consumer Commission, GPO Box 3131, Canberra ACT 2601, Australia',
    reportingUrl: 'https://www.scamwatch.gov.au/report-a-scam',
    description: 'Australia\'s scam reporting platform operated by the Australian Competition and Consumer Commission (ACCC). Allows citizens to report scams, provides real-time scam alerts, and publishes research on scam trends affecting Australians.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-fr-001',
    name: 'PHAROS (Platform for Reporting Illegal Online Content)',
    country: 'France',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://www.interieur.gouv.fr',
    phone: null,
    email: null,
    address: 'Ministere de lInterieur, Paris, France',
    reportingUrl: 'https://www.internet-signalement.gouv.fr',
    description: 'Frances national platform for reporting cybercrime including online fraud, identity theft, and illegal content. Managed by the Ministry of Interior.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-fr-002',
    name: 'Cybermalveillance.gouv.fr',
    country: 'France',
    type: 'government',
    category: 'cyber_cell',
    website: 'https://www.cybermalveillance.gouv.fr',
    phone: null,
    email: null,
    address: 'SGDSN, Paris, France',
    reportingUrl: 'https://www.cybermalveillance.gouv.fr/tous-nos-contenus/contenus-et-fiches-pratiques',
    description: 'French government platform providing assistance to victims of cyberattacks and digital threats.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-jp-001',
    name: 'National Police Agency - Cybercrime Division',
    country: 'Japan',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://www.npa.go.jp',
    phone: '#9110',
    email: null,
    address: 'National Police Agency, Kasumigaseki, Chiyoda-ku, Tokyo, Japan',
    reportingUrl: 'https://www.npa.go.jp/sosakaihogo/goanjin/',
    description: 'Japans National Police Agency handles cybercrime investigations including online fraud, phishing, and identity theft.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-jp-002',
    name: 'JPCERT/CC (Japan Computer Emergency Response Team)',
    country: 'Japan',
    type: 'government',
    category: 'cyber_cell',
    website: 'https://www.jpcert.or.jp',
    phone: '+81-3-5280-7111',
    email: 'info@jpcert.or.jp',
    address: 'JPCERT/CC, Chiyoda-ku, Tokyo, Japan',
    reportingUrl: 'https://www.jpcert.or.jp/english/',
    description: 'Japans computer emergency response team coordinates incident response for cyber threats.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-cn-001',
    name: 'Ministry of Public Security - Cybersecurity Bureau',
    country: 'China',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://www.mps.gov.cn',
    phone: '110',
    email: null,
    address: 'Ministry of Public Security, Dongcheng District, Beijing, China',
    reportingUrl: 'https://www.12321.cn',
    description: 'Chinas primary law enforcement agency for cybercrime investigation. Handles online fraud, hacking, identity theft.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-cn-002',
    name: '12321 Internet Reporting Center',
    country: 'China',
    type: 'government',
    category: 'consumer_protection',
    website: 'https://www.12321.cn',
    phone: null,
    email: null,
    address: 'China Internet Association, Beijing',
    reportingUrl: 'https://www.12321.cn',
    description: 'Chinas national center for reporting spam, scam messages, fraudulent websites, and illegal internet content.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-br-001',
    name: 'Policia Federal - Cybercrime Division',
    country: 'Brazil',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://www.pf.gov.br',
    phone: '+55-61-2024-8000',
    email: null,
    address: 'Policia Federal, SAF Quadra 04, Brasilia, DF, Brazil',
    reportingUrl: 'https://www.pf.gov.br/servicos/fale-conosco',
    description: 'Brazils Federal Police cybercrime division investigates online fraud, hacking, identity theft, and electronic financial crimes.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-br-002',
    name: 'CERT.br (Centro de Estudos e Resposta de Incidentes)',
    country: 'Brazil',
    type: 'government',
    category: 'cyber_cell',
    website: 'https://cert.br',
    phone: '+55-11-3243-1020',
    email: 'cert@cert.br',
    address: 'NIC.br, Sao Paulo, Brazil',
    reportingUrl: 'https://cert.br/incidentes/',
    description: 'Brazils national CERT handles cybersecurity incident response and provides guidance on cyber threats.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-ng-001',
    name: 'Nigeria Police Force - Cybercrime Unit',
    country: 'Nigeria',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://www.npf.gov.ng',
    phone: '+234-809-200-0001',
    email: null,
    address: 'Nigeria Police Force HQ, Louis Edet House, Abuja, Nigeria',
    reportingUrl: 'https://www.npf.gov.ng/report-crime',
    description: 'Nigerias police cybercrime unit investigates online fraud, identity theft, and electronic financial crimes.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-ng-002',
    name: 'Economic and Financial Crimes Commission (EFCC)',
    country: 'Nigeria',
    type: 'law_enforcement',
    category: 'consumer_protection',
    website: 'https://www.efccnigeria.org',
    phone: '+234-809-200-0001',
    email: 'info@efccnigeria.org',
    address: 'EFCC HQ, Central Business District, Abuja, Nigeria',
    reportingUrl: 'https://www.efccnigeria.org/efcc/index.php/contact-us',
    description: 'Nigerias premier anti-fraud agency investigating economic and financial crimes including online fraud and cyber-enabled financial crimes.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-za-001',
    name: 'South African Police Service (SAPS) - Cybercrime Unit',
    country: 'South Africa',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://www.saps.gov.za',
    phone: '10111',
    email: null,
    address: 'SAPS HQ, 550 Pretorius Street, Pretoria, South Africa',
    reportingUrl: 'https://www.saps.gov.za/services/crime_report.php',
    description: 'South Africas national police cybercrime unit investigates online fraud, hacking, identity theft, and electronic crimes.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-sa-001',
    name: 'Saudi Federation for Cybersecurity (SAFCSP)',
    country: 'Saudi Arabia',
    type: 'government',
    category: 'cyber_cell',
    website: 'https://www.safcsp.org.sa',
    phone: '999',
    email: null,
    address: 'Riyadh, Saudi Arabia',
    reportingUrl: 'https://www.safcsp.org.sa',
    description: 'Saudi Arabias national cybersecurity authority responsible for cyber threat response and incident reporting.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-sa-002',
    name: 'National Cyber Security Commission (NCSC)',
    country: 'Saudi Arabia',
    type: 'government',
    category: 'cyber_cell',
    website: 'https://www.ncsc.gov.sa',
    phone: null,
    email: null,
    address: 'Riyadh, Saudi Arabia',
    reportingUrl: 'https://www.ncsc.gov.sa',
    description: 'Saudi Arabias National Cyber Security Commission oversees national cybersecurity strategy and coordinates incident response.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-tr-001',
    name: 'Information and Communication Technologies Authority (BTK)',
    country: 'Turkey',
    type: 'government',
    category: 'cyber_cell',
    website: 'https://www.btk.gov.tr',
    phone: '+90-312-231-60-00',
    email: 'bilgi@btk.gov.tr',
    address: 'BTK, Universiteler Mahallesi, Ankara, Turkey',
    reportingUrl: 'https://www.btk.gov.tr/tr-TR/ihbar',
    description: 'Turkeys telecom and internet regulator handles cybercrime reporting, website blocking requests, and cybersecurity resources.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-tr-002',
    name: 'Turkish National Police - Cyber Crimes Branch',
    country: 'Turkey',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://www.egm.gov.tr',
    phone: '155',
    email: null,
    address: 'Turkish National Police HQ, Ankara, Turkey',
    reportingUrl: 'https://www.egm.gov.tr',
    description: 'Turkeys national police cyber crimes branch investigates online fraud, hacking, and electronic crimes.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-id-001',
    name: 'BSSN (Badan Siber dan Sandi Negara)',
    country: 'Indonesia',
    type: 'government',
    category: 'cyber_cell',
    website: 'https://www.bssn.go.id',
    phone: '+62-21-1500035',
    email: 'humas@bssn.go.id',
    address: 'BSSN, Jakarta, Indonesia',
    reportingUrl: 'https://www.bssn.go.id/lapor',
    description: 'Indonesias National Cyber and Crypto Agency responsible for cybersecurity policy, incident response, and cyber threat management.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-mx-001',
    name: 'Policia Federal - Division de Cibercrimen',
    country: 'Mexico',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://www.gob.mx/guardianacional',
    phone: '088',
    email: null,
    address: 'Guardia Nacional, Mexico City, Mexico',
    reportingUrl: 'https://www.gob.mx/guardianacional',
    description: 'Mexicos federal police cybercrime division investigates online fraud, hacking, and digital crimes.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-mx-002',
    name: 'CERT-MX (Computer Emergency Response Team Mexico)',
    country: 'Mexico',
    type: 'government',
    category: 'cyber_cell',
    website: 'https://www.cert.mx',
    phone: '+52-55-5283-0500',
    email: 'contacto@cert.mx',
    address: 'CERT-MX, Mexico City, Mexico',
    reportingUrl: 'https://www.cert.mx/reportar',
    description: 'Mexicos national CERT handles cybersecurity incident response, provides guidance, and coordinates with international CERTs.',
    verificationStatus: 'verified',
  },
  {
    id: 'ca-ru-001',
    name: 'Ministry of Internal Affairs - Cybercrime Unit (K)',
    country: 'Russia',
    type: 'law_enforcement',
    category: 'cyber_cell',
    website: 'https://мвд.рф',
    phone: '102',
    email: null,
    address: 'MVD, Moscow, Russia',
    reportingUrl: 'https://мвд.рф/report',
    description: 'Russias Ministry of Internal Affairs cybercrime unit (Directorate K) investigates online fraud, hacking, and electronic crimes.',
    verificationStatus: 'verified',
  },
];

const complaintProcedures = [
  {
    id: 'cp-pk-001',
    authorityId: 'ca-pk-001',
    country: 'Pakistan',
    category: 'cybercrime_filing',
    procedureSteps: JSON.stringify([
      'Visit the FIA Cyber Crime Wing online complaint portal at complaint.fia.gov.pk',
      'Create an account with your CNIC number, email, and phone number',
      'Select the type of cybercrime from the available categories (fraud, harassment, identity theft, etc.)',
      'Provide a detailed description of the incident with dates and timeline',
      'Upload all supporting evidence: screenshots of messages, emails, transaction receipts, bank statements',
      'Submit the complaint and note down the complaint reference number',
      'FIA will review the complaint within 24-48 hours and assign it to an investigation officer',
      'You may be contacted for additional information or to provide a formal statement',
      'Track your complaint status online using the reference number'
    ]),
    requiredDocuments: 'Valid CNIC, screenshots of fraudulent messages/emails, bank transaction records, phone call recordings (if available), any communication with the fraudster',
    estimatedTime: '24-48 hours for initial response; investigation may take weeks to months',
    cost: null,
    sourceUrl: 'https://complaint.fia.gov.pk',
  },
  {
    id: 'cp-us-001',
    authorityId: 'ca-us-001',
    country: 'United States',
    category: 'ftc_complaint',
    procedureSteps: JSON.stringify([
      'Go to reportfraud.ftc.gov',
      'Select "Report Fraud" and choose the category of fraud (online shopping, imposter, phone/internet, etc.)',
      'Provide details about what happened: who contacted you, how they reached you, what they wanted',
      'Enter financial loss details if applicable (amount, payment method, date)',
      'Upload supporting documents and evidence',
      'Provide your contact information for follow-up',
      'Submit the report and save your Report ID for reference',
      'FTC may refer your case to law enforcement partners for investigation'
    ]),
    requiredDocuments: 'Description of the fraud incident, financial records, copies of communications with the scammer, email headers, phone numbers used',
    estimatedTime: 'Report processed immediately; no individual case follow-up unless referred to law enforcement',
    cost: null,
    sourceUrl: 'https://reportfraud.ftc.gov',
  },
  {
    id: 'cp-us-002',
    authorityId: 'ca-us-002',
    country: 'United States',
    category: 'ic3_complaint',
    procedureSteps: JSON.stringify([
      'Visit www.ic3.gov and click "File a Complaint"',
      'Review the IC3 complaint information and disclaimer',
      'Enter victim information (name, address, contact details)',
      'Provide detailed information about the internet crime: type, date, timeline, financial impact',
      'Include the subject information: names, email addresses, phone numbers, website URLs of the suspect',
      'Upload relevant files: screenshots, emails, transaction records, chat logs',
      'Review and submit the complaint',
      'Receive a confirmation with your IC3 complaint number',
      'Your complaint will be analyzed and potentially referred to the appropriate law enforcement agency'
    ]),
    requiredDocuments: 'Valid identification, detailed incident timeline, financial loss documentation, email communications, website URLs, phone records',
    estimatedTime: 'Complaint processed immediately; investigation referral varies by case severity',
    cost: null,
    sourceUrl: 'https://www.ic3.gov/Home/ComplaintChoice',
  },
  {
    id: 'cp-uk-001',
    authorityId: 'ca-uk-001',
    country: 'United Kingdom',
    category: 'action_fraud_reporting',
    procedureSteps: JSON.stringify([
      'Visit www.actionfraud.police.uk',
      'Click "Report a Fraud or Cyber Crime"',
      'Select the type of fraud from the available categories',
      'Provide personal details and contact information',
      'Describe the fraud in detail: how it happened, when, what was lost',
      'Include suspect details if available (names, phone numbers, emails, addresses)',
      'Upload evidence files: bank statements, emails, screenshots',
      'Review and submit your report',
      'Receive a crime reference number for your records',
      'Report is forwarded to the National Fraud Intelligence Bureau for analysis and police allocation'
    ]),
    requiredDocuments: 'Valid ID, bank statements showing fraudulent transactions, copies of phishing emails or scam letters, screenshots of scam websites',
    estimatedTime: 'Report processed within 24 hours; investigation timeline depends on case priority',
    cost: null,
    sourceUrl: 'https://www.actionfraud.police.uk/reporting-fraud-and-cyber-crime',
  },
  {
    id: 'cp-in-001',
    authorityId: 'ca-in-001',
    country: 'India',
    category: 'cyber_crime_portal',
    procedureSteps: JSON.stringify([
      'Visit cybercrime.gov.in and click "Report Cyber Crime"',
      'Select "Report Other Cyber Crime" or "Report Women/Child Related Crime"',
      'Register/login using your mobile number and OTP',
      'Select the appropriate cybercrime category (financial fraud, identity theft, cyberstalking, etc.)',
      'Fill in incident details: date, time, description, financial loss amount',
      'Provide suspect information if available',
      'Upload all supporting evidence: screenshots, transaction receipts, emails',
      'Choose the police station for jurisdiction or let the system assign based on your location',
      'Submit the complaint and save the complaint reference number',
      'Track status at cybercrime.gov.in using your credentials'
    ]),
    requiredDocuments: 'Valid government ID, bank transaction details, screenshots of fraudulent communication, email/sms content, device details if hacked',
    estimatedTime: 'Complaint acknowledged within 24 hours; investigation initiated within 7 days',
    cost: null,
    sourceUrl: 'https://cybercrime.gov.in',
  },
  {
    id: 'cp-ae-001',
    authorityId: 'ca-ae-001',
    country: 'United Arab Emirates',
    category: 'online_reporting',
    procedureSteps: JSON.stringify([
      'Visit the Dubai Police website or mobile app',
      'Navigate to "Services" then "Report Cyber Crime"',
      'Select the type of cyber crime (electronic fraud, identity theft, online blackmail, etc.)',
      'Fill in personal details and Emirates ID number',
      'Provide detailed incident description',
      'Include suspect information: phone numbers, email addresses, bank accounts',
      'Upload all supporting documents and evidence',
      'Submit the report and receive a reference number',
      'Dubai Police will investigate and may contact you for additional information',
      'For emergencies or financial fraud, also call 901 immediately'
    ]),
    requiredDocuments: 'Emirates ID, bank statements, transaction records, screenshots of fraudulent messages, email communications',
    estimatedTime: 'Initial response within 48 hours; investigation timeline depends on case complexity',
    cost: null,
    sourceUrl: 'https://www.dubaipolice.gov.ae',
  },
  {
    id: 'cp-general-bank-001',
    authorityId: 'ca-pk-001',
    country: 'Pakistan',
    category: 'bank_fraud',
    procedureSteps: JSON.stringify([
      'Immediately contact your bank\'s fraud/hotline department using the number on the back of your card',
      'Freeze or block the compromised card/account to prevent further unauthorized transactions',
      'File a formal written complaint with your bank\'s fraud department',
      'Provide all transaction details: dates, amounts, reference numbers, recipient details',
      'Request a chargeback or reversal for unauthorized transactions',
      'Report the fraud to your local cybercrime/police authority',
      'Change all passwords associated with your banking accounts',
      'Enable two-factor authentication on all financial accounts',
      'Monitor your credit report for unauthorized accounts opened in your name',
      'Keep copies of all correspondence with the bank and authorities'
    ]),
    requiredDocuments: 'Bank account/card details, transaction records/receipts, police/cybercrime complaint reference number, written complaint to bank, ID proof',
    estimatedTime: 'Immediate card freeze within minutes; chargeback process takes 30-90 days; police investigation varies',
    cost: null,
    sourceUrl: null,
  },
  {
    id: 'cp-general-email-001',
    authorityId: 'ca-us-001',
    country: 'United States',
    category: 'email_fraud',
    procedureSteps: JSON.stringify([
      'Do NOT reply to the fraudulent email or click any links in it',
      'Take screenshots of the entire email including email headers (full source/raw headers)',
      'Report the email as phishing/spam in your email client (Gmail, Outlook, etc.)',
      'Forward the phishing email to reportphishing@apwg.org (Anti-Phishing Working Group)',
      'If the email claims to be from a known company, forward it to that company\'s abuse/security team',
      'Report the fraud to your local cybercrime authority with all evidence',
      'If you clicked a link or provided information, immediately change all affected passwords',
      'Run a full antivirus/malware scan on your device',
      'Enable email filtering and enhanced security features on your account',
      'If financial information was shared, contact your bank immediately'
    ]),
    requiredDocuments: 'Full email with headers (not just screenshot), screenshots of phishing website (if visited), any information entered on fake site, timeline of events',
    estimatedTime: 'Reporting takes 15-30 minutes; email provider action within 24-48 hours; law enforcement response varies',
    cost: null,
    sourceUrl: null,
  },
  {
    id: 'cp-general-phone-001',
    authorityId: 'ca-pk-001',
    country: 'Pakistan',
    category: 'phone_sms_fraud',
    procedureSteps: JSON.stringify([
      'Do NOT share any personal or financial information over the call or SMS',
      'Hang up immediately if the call seems suspicious',
      'Note down the phone number, time of call, and what was said',
      'Take screenshots of any suspicious SMS messages',
      'Do NOT click any links sent via SMS',
      'Block the number on your phone',
      'Report the number to your mobile carrier (forward SMS to 7726 in Pakistan)',
      'If money was transferred, contact your bank immediately to freeze/reverse the transaction',
      'File a report with your local cybercrime authority',
      'Warn family and friends about the scam to prevent further victims'
    ]),
    requiredDocuments: 'Phone number used by scammer, SMS screenshots, call log records, transaction details (if money was lost), any audio recordings of calls',
    estimatedTime: 'Immediate block within minutes; carrier report processed within 24 hours; investigation varies',
    cost: null,
    sourceUrl: null,
  },
  {
    id: 'cp-fr-001',
    authorityId: 'ca-fr-001',
    country: 'France',
    category: 'cybercrime_filing',
    procedureSteps: JSON.stringify([
      'Visit internet-signalement.gouv.fr',
      'Click on Signaler and create an account or login',
      'Select the type of illegal content (fraud, phishing, identity theft)',
      'Provide detailed description of the incident',
      'Upload evidence: screenshots, emails, transaction records',
      'Submit the report and save the reference number',
      'PHAROS will analyze and route to appropriate law enforcement'
    ]),
    requiredDocuments: 'Valid ID, screenshots of fraud, bank statements, email communications',
    estimatedTime: 'Report processed within 48 hours',
    cost: null,
    sourceUrl: 'https://www.internet-signalement.gouv.fr',
  },
  {
    id: 'cp-jp-001',
    authorityId: 'ca-jp-001',
    country: 'Japan',
    category: 'cybercrime_filing',
    procedureSteps: JSON.stringify([
      'Call #9110 (cybercrime consultation hotline) or visit your local police station',
      'Provide details of the cybercrime incident',
      'Submit evidence: screenshots, emails, transaction records',
      'Police will file a report and assign a case number',
      'For online fraud, also report to the platform where the fraud occurred'
    ]),
    requiredDocuments: 'Valid ID, screenshots, bank statements, communication records',
    estimatedTime: 'Immediate consultation; investigation varies by case',
    cost: null,
    sourceUrl: 'https://www.npa.go.jp',
  },
  {
    id: 'cp-cn-001',
    authorityId: 'ca-cn-001',
    country: 'China',
    category: 'cybercrime_filing',
    procedureSteps: JSON.stringify([
      'Visit 12321.cn for internet fraud and spam reporting',
      'Or call 110 for emergency cybercrime reporting',
      'Provide incident details and suspect information',
      'Upload evidence: screenshots, transaction records, communications',
      'Receive a case reference number',
      'For financial fraud, also contact your bank immediately'
    ]),
    requiredDocuments: 'Valid ID, screenshots, bank records, communication evidence',
    estimatedTime: 'Immediate for emergency; investigation varies',
    cost: null,
    sourceUrl: 'https://www.12321.cn',
  },
  {
    id: 'cp-br-001',
    authorityId: 'ca-br-001',
    country: 'Brazil',
    category: 'cybercrime_filing',
    procedureSteps: JSON.stringify([
      'Visit delegacia Virtual in your state or pf.gov.br for federal crimes',
      'Register a Boletim de Ocorrencia (police report) online',
      'Select the crime type: estelionato (fraud), furto (theft), etc.',
      'Provide detailed incident description',
      'Upload evidence: screenshots, bank statements, communications',
      'Save the protocol number for tracking',
      'For financial fraud, contact your bank immediately'
    ]),
    requiredDocuments: 'CPF (tax ID), screenshots, bank statements, communication records',
    estimatedTime: 'Report filed immediately; investigation varies',
    cost: null,
    sourceUrl: 'https://www.pf.gov.br',
  },
  {
    id: 'cp-ng-001',
    authorityId: 'ca-ng-002',
    country: 'Nigeria',
    category: 'cybercrime_filing',
    procedureSteps: JSON.stringify([
      'Visit efccnigeria.org and click Report a Crime',
      'Or visit the nearest EFCC office with your evidence',
      'Provide full details of the fraud: who, what, when, how much',
      'Submit all evidence: screenshots, bank records, communications',
      'EFCC will review and may contact you for additional information',
      'You can also call the EFCC hotline for urgent cases'
    ]),
    requiredDocuments: 'Valid ID, bank statements, screenshots of fraud, communication records',
    estimatedTime: 'Initial review within 7 days; investigation varies',
    cost: null,
    sourceUrl: 'https://www.efccnigeria.org',
  },
  {
    id: 'cp-za-001',
    authorityId: 'ca-za-001',
    country: 'South Africa',
    category: 'cybercrime_filing',
    procedureSteps: JSON.stringify([
      'Visit your nearest police station or call 10111',
      'Report the cybercrime to the investigating officer',
      'Provide a detailed statement describing the incident',
      'Submit evidence: screenshots, bank statements, communications',
      'Receive a case number (CAS number)',
      'The case will be assigned to the cybercrime unit for investigation'
    ]),
    requiredDocuments: 'Valid ID, bank statements, screenshots, communication records',
    estimatedTime: 'Case opened immediately; investigation varies',
    cost: null,
    sourceUrl: 'https://www.saps.gov.za',
  },
  {
    id: 'cp-sa-001',
    authorityId: 'ca-sa-001',
    country: 'Saudi Arabia',
    category: 'cybercrime_filing',
    procedureSteps: JSON.stringify([
      'Call 999 for emergency cybercrime reporting',
      'Or visit the nearest police station',
      'Provide your Iqama/ID and details of the incident',
      'Submit evidence: screenshots, bank records, communications',
      'For online fraud, also report to your bank immediately',
      'You can also report through the Absher platform'
    ]),
    requiredDocuments: 'Valid Iqama/ID, bank statements, screenshots, communication records',
    estimatedTime: 'Immediate for emergency; investigation varies',
    cost: null,
    sourceUrl: 'https://www.safcsp.org.sa',
  },
  {
    id: 'cp-tr-001',
    authorityId: 'ca-tr-001',
    country: 'Turkey',
    category: 'cybercrime_filing',
    procedureSteps: JSON.stringify([
      'Visit btk.gov.tr/tr-TR/ihbar for online reporting',
      'Or call 155 (Police) or 156 (Gendarmerie)',
      'Select the type of cybercrime',
      'Provide detailed incident description',
      'Upload evidence: screenshots, bank records, communications',
      'Receive a reference number for tracking'
    ]),
    requiredDocuments: 'Valid ID (Kimlik), bank statements, screenshots, communication records',
    estimatedTime: 'Report filed immediately; investigation varies',
    cost: null,
    sourceUrl: 'https://www.btk.gov.tr/tr-TR/ihbar',
  },
  {
    id: 'cp-id-001',
    authorityId: 'ca-id-001',
    country: 'Indonesia',
    category: 'cybercrime_filing',
    procedureSteps: JSON.stringify([
      'Visit bssn.go.id/lapor for cyber incident reporting',
      'Or call the BSSN hotline at 1500035',
      'Register your complaint with personal details',
      'Describe the cybercrime incident in detail',
      'Upload evidence: screenshots, transaction records, communications',
      'For financial fraud, also report to your bank and call 110'
    ]),
    requiredDocuments: 'Valid KTP (ID), bank statements, screenshots, communication records',
    estimatedTime: 'Initial response within 3 days; investigation varies',
    cost: null,
    sourceUrl: 'https://www.bssn.go.id/lapor',
  },
  {
    id: 'cp-mx-001',
    authorityId: 'ca-mx-001',
    country: 'Mexico',
    category: 'cybercrime_filing',
    procedureSteps: JSON.stringify([
      'Call 088 (Denuncia Digital) or visit guardanacional.gob.mx',
      'Select the type of cybercrime',
      'Provide your details and incident description',
      'Upload evidence: screenshots, bank records, communications',
      'Receive a case number for tracking',
      'For financial fraud, also contact your bank (CNBV) immediately'
    ]),
    requiredDocuments: 'Valid INE/IFE ID, bank statements, screenshots, communication records',
    estimatedTime: 'Report filed immediately; investigation varies',
    cost: null,
    sourceUrl: 'https://www.gob.mx/guardianacional',
  },
  {
    id: 'cp-ru-001',
    authorityId: 'ca-ru-001',
    country: 'Russia',
    category: 'cybercrime_filing',
    procedureSteps: JSON.stringify([
      'Call 102 (Police) for immediate cybercrime reporting',
      'Or visit the nearest police station (OVD)',
      'File a formal statement describing the cybercrime',
      'Submit evidence: screenshots, bank records, communications',
      'Receive a case registration number (KUSP)',
      'The case will be assigned to Directorate K for investigation'
    ]),
    requiredDocuments: 'Valid passport, bank statements, screenshots, communication records',
    estimatedTime: 'Report filed within 3 days; investigation varies',
    cost: null,
    sourceUrl: null,
  },
];

async function main() {
  console.log('Starting fraud seed...\n');

  // Clear existing data
  console.log('Clearing existing complaint procedures and cyber authorities...');
  await prisma.complaintProcedure.deleteMany();
  await prisma.cyberAuthority.deleteMany();

  // Seed cyber authorities
  console.log('Seeding cyber authorities...');
  for (const authority of cyberAuthorities) {
    await prisma.cyberAuthority.create({
      data: {
        id: authority.id,
        name: authority.name,
        country: authority.country,
        type: authority.type,
        category: authority.category,
        website: authority.website,
        phone: authority.phone,
        email: authority.email,
        address: authority.address,
        reportingUrl: authority.reportingUrl,
        description: authority.description,
        verificationStatus: authority.verificationStatus,
      },
    });
  }
  console.log(`  ✓ ${cyberAuthorities.length} cyber authorities seeded`);

  // Seed complaint procedures
  console.log('Seeding complaint procedures...');
  for (const procedure of complaintProcedures) {
    await prisma.complaintProcedure.create({
      data: {
        id: procedure.id,
        authorityId: procedure.authorityId,
        country: procedure.country,
        category: procedure.category,
        procedureSteps: procedure.procedureSteps,
        requiredDocuments: procedure.requiredDocuments,
        estimatedTime: procedure.estimatedTime,
        sourceUrl: procedure.sourceUrl,
      },
    });
  }
  console.log(`  ✓ ${complaintProcedures.length} complaint procedures seeded`);

  console.log('\nFraud seed data created successfully!');
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
