import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const institutions = [
  {
    name: 'NAVTTC (National Vocational & Technical Training Commission)',
    type: 'govt',
    description: 'Pakistan\'s apex regulatory body for technical and vocational education and training. Provides free certification courses in IT, construction, health, agriculture, and industrial trades across Pakistan.',
    website: 'https://navttc.gov.pk',
    location: 'Islamabad (HQ), Regional Centers across Pakistan',
    province: 'all',
    contactEmail: 'info@navttc.gov.pk',
    contactPhone: '+92-51-9263132',
    eligibilityCriteria: 'Age 18-40 years. Minimum Matriculation education. Must be Pakistani citizen. Must not be currently employed in similar trade. Preference to unemployed youth.',
    applicationProcess: 'Apply online at navttc.gov.pk or visit nearest NAVTTC center. Register for preferred course. Appear for basic aptitude test. Shortlisted candidates enrolled in 3-12 month training programs.',
    status: 'active',
    sourceUrl: 'https://navttc.gov.pk',
    sourceName: 'NAVTTC Official',
    verificationStatus: 'verified',
    courses: [
      { name: 'Web Development & Design', duration: '6 months', description: 'HTML, CSS, JavaScript, React, Node.js, database management', fee: 'Free (with monthly stipend)', certification: 'NAVTTC Certified Web Developer', batchStart: 'January, April, July, October' },
      { name: 'Mobile App Development', duration: '6 months', description: 'Android/iOS development with Kotlin/Swift, UI/UX design', fee: 'Free (with monthly stipend)', certification: 'NAVTTC Certified Mobile Developer', batchStart: 'January, April, July, October' },
      { name: 'Digital Marketing', duration: '3 months', description: 'SEO, SEM, social media marketing, content marketing, analytics', fee: 'Free (with monthly stipend)', certification: 'NAVTTC Certified Digital Marketer', batchStart: 'January, April, July, October' },
      { name: 'Cybersecurity Fundamentals', duration: '6 months', description: 'Network security, ethical hacking, penetration testing, compliance', fee: 'Free (with monthly stipend)', certification: 'NAVTTC Certified Cybersecurity Professional', batchStart: 'January, April, July, October' },
      { name: 'Electrician & Solar Installation', duration: '3 months', description: 'Electrical wiring, solar panel installation, inverter maintenance', fee: 'Free (with monthly stipend)', certification: 'NAVTTC Certified Electrician', batchStart: 'January, April, July, October' },
      { name: 'Plumbing & Pipe Fitting', duration: '3 months', description: 'Residential and commercial plumbing, pipe fitting, water systems', fee: 'Free (with monthly stipend)', certification: 'NAVTTC Certified Plumber', batchStart: 'January, April, July, October' },
    ],
    entryTests: [
      {
        testName: 'NAVTTC General Aptitude Test',
        type: 'aptitude',
        totalMarks: 100,
        passingMarks: 50,
        passingPercentage: '50%',
        syllabus: 'General knowledge, basic mathematics, English comprehension, analytical reasoning, trade-specific questions',
        preparationTips: 'Practice basic math (percentages, ratios, fractions). Read English comprehension passages. Study trade-specific fundamentals. Use NAVTTC past papers available on website.',
      },
    ],
    documents: [
      { documentName: 'CNIC', description: 'Valid National Identity Card', isRequired: true },
      { documentName: 'Educational Certificates', description: 'Matric and above certificates/marksheets', isRequired: true },
      { documentName: 'Domicile Certificate', description: 'Provincial domicile', isRequired: false },
      { documentName: 'Photographs', description: '4 recent passport-size photographs', isRequired: true },
      { documentName: 'Experience Certificate', description: 'Any prior work experience certificates (if applicable)', isRequired: false },
    ],
  },
  {
    name: 'PSDF (Pakistan Skills Development Fund)',
    type: 'govt',
    description: 'Federal government skills development fund providing free technical and vocational training. Partners with private sector to deliver industry-relevant courses. Covers IT, construction, health, hospitality, and manufacturing sectors.',
    website: 'https://psdf.org.pk',
    location: 'Lahore (HQ), Training centers across Pakistan',
    province: 'all',
    contactEmail: 'info@psdf.org.pk',
    contactPhone: '+92-42-35782200',
    eligibilityCriteria: 'Age 18-45 years. Minimum education: Middle (8th grade). Must be Pakistani citizen. Must be unemployed or earning below PKR 25,000/month. Priority to women and persons with disabilities.',
    applicationProcess: 'Apply through PSDF partner institutes or online portal. Register for preferred course. Appear for entrance assessment. Selected candidates enrolled in training program. Training provided free with stipend.',
    status: 'active',
    sourceUrl: 'https://psdf.org.pk',
    sourceName: 'PSDF Official',
    verificationStatus: 'verified',
    courses: [
      { name: 'Advanced IT & Software Development', duration: '6 months', description: 'Python, Java, database management, software engineering', fee: 'Free', certification: 'PSDF Industry-Recognized Certificate', batchStart: 'January, March, June, September' },
      { name: 'Data Science & Analytics', duration: '6 months', description: 'Data analysis, machine learning basics, visualization tools', fee: 'Free', certification: 'PSDF Data Analytics Certificate', batchStart: 'January, March, June, September' },
      { name: 'Graphic Design & Video Editing', duration: '3 months', description: 'Adobe Creative Suite, motion graphics, video production', fee: 'Free', certification: 'PSDF Creative Professional Certificate', batchStart: 'January, March, June, September' },
      { name: 'Healthcare Assistant', duration: '6 months', description: 'First aid, patient care, medical terminology, pharmacy basics', fee: 'Free', certification: 'PSDF Healthcare Certificate', batchStart: 'January, March, June, September' },
      { name: 'Construction & Masonry', duration: '3 months', description: 'Building construction, masonry, carpentry, safety protocols', fee: 'Free', certification: 'PSDF Construction Certificate', batchStart: 'January, March, June, September' },
      { name: 'Automotive Repair & Maintenance', duration: '6 months', description: 'Engine repair, electrical systems, diagnostics, maintenance', fee: 'Free', certification: 'PSDF Automotive Certificate', batchStart: 'January, March, June, September' },
    ],
    entryTests: [
      {
        testName: 'PSDF Skills Assessment Test',
        type: 'aptitude',
        totalMarks: 100,
        passingMarks: 40,
        passingPercentage: '40%',
        syllabus: 'Basic numeracy, reading comprehension, logical reasoning, trade-specific questions',
        preparationTips: 'Focus on basic math skills (addition, subtraction, multiplication, division). Practice reading comprehension. Review trade-specific basics. PSDF provides free pre-training on website.',
      },
    ],
    documents: [
      { documentName: 'CNIC', description: 'Valid National Identity Card', isRequired: true },
      { documentName: 'Educational Certificates', description: 'Middle/Matric/Intermediate certificates', isRequired: true },
      { documentName: 'Income Certificate', description: 'Income proof or unemployment certificate', isRequired: false },
      { documentName: 'Disability Certificate', description: 'If applicable, disability certificate from NADRA', isRequired: false },
      { documentName: 'Photographs', description: '4 recent passport-size photographs', isRequired: true },
    ],
  },
  {
    name: 'Saylani Welfare Trust (Mass IT Training Program)',
    type: 'ngo',
    description: 'One of Pakistan\'s largest NGOs providing free IT training to unemployed youth. Offers courses in web development, graphic design, data entry, and digital marketing. Training centers in Karachi, Lahore, Islamabad, and other cities.',
    website: 'https://saylaniwelfare.com',
    location: 'Karachi (HQ), Lahore, Islamabad, Peshawar, Faisalabad',
    province: 'all',
    contactEmail: 'training@saylaniwelfare.com',
    contactPhone: '+92-21-34980400',
    eligibilityCriteria: 'Age 18-35 years. Minimum Matriculation education. Must be unemployed or earning below PKR 20,000/month. Must be willing to attend regular classes (3-6 months). No criminal record.',
    applicationProcess: 'Visit nearest Saylani center. Fill registration form. Appear for basic IT assessment. Shortlisted candidates enrolled in next batch. Classes held 5 days a week for 3-6 months.',
    status: 'active',
    sourceUrl: 'https://saylaniwelfare.com/training',
    sourceName: 'Saylani Welfare Trust',
    verificationStatus: 'verified',
    courses: [
      { name: 'Web Development Bootcamp', duration: '6 months', description: 'HTML, CSS, JavaScript, React, Node.js, MongoDB, deployment', fee: 'Free', certification: 'Saylani IT Certificate', batchStart: 'Monthly enrollment' },
      { name: 'Graphic Design Mastery', duration: '3 months', description: 'Photoshop, Illustrator, InDesign, UI/UX principles', fee: 'Free', certification: 'Saylani IT Certificate', batchStart: 'Monthly enrollment' },
      { name: 'Data Entry & Office Management', duration: '3 months', description: 'MS Office, data entry speed training, filing systems', fee: 'Free', certification: 'Saylani IT Certificate', batchStart: 'Monthly enrollment' },
      { name: 'Digital Marketing & Social Media', duration: '3 months', description: 'Google Ads, Facebook marketing, Instagram growth, analytics', fee: 'Free', certification: 'Saylani IT Certificate', batchStart: 'Monthly enrollment' },
      { name: 'Freelancing & Earning Online', duration: '2 months', description: 'Upwork, Fiverr, Freelancer profiles, bidding, client management', fee: 'Free', certification: 'Saylani Freelancing Certificate', batchStart: 'Monthly enrollment' },
      { name: 'English Language Course', duration: '3 months', description: 'Basic to intermediate English, speaking, writing, grammar', fee: 'Free', certification: 'Saylani English Certificate', batchStart: 'Monthly enrollment' },
    ],
    entryTests: [
      {
        testName: 'Saylani Basic IT Assessment',
        type: 'aptitude',
        totalMarks: 50,
        passingMarks: 20,
        passingPercentage: '40%',
        syllabus: 'Basic computer knowledge, typing speed, simple English comprehension, general aptitude',
        preparationTips: 'Practice typing (aim for 20 WPM). Learn basic computer operations. Study simple English grammar. Saylani provides free pre-assessment practice materials at center.',
      },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document', isRequired: true },
      { documentName: 'Educational Certificates', description: 'Matric certificate or equivalent', isRequired: true },
      { documentName: 'Photographs', description: '4 passport-size photographs', isRequired: true },
      { documentName: 'Income Certificate', description: 'Income proof or unemployment letter (if available)', isRequired: false },
    ],
  },
  {
    name: 'Ignite (National Technology Fund)',
    type: 'govt',
    description: 'Federal government initiative to promote innovation and technology in Pakistan. Provides free training programs, startup incubation, and technology grants. Focuses on emerging technologies like AI, blockchain, and IoT.',
    website: 'https://ignite.gov.pk',
    location: 'Islamabad (HQ), Regional offices in Lahore, Karachi',
    province: 'all',
    contactEmail: 'info@ignite.gov.pk',
    contactPhone: '+92-51-9213444',
    eligibilityCriteria: 'Age 18-35 years. Minimum Bachelor\'s degree for advanced courses. Must be Pakistani citizen. Must have basic computer literacy. For startup programs: must have innovative tech idea.',
    applicationProcess: 'Apply through Ignite website or partner institutes. Submit application with CV and motivation letter. Shortlisted candidates appear for technical interview. Selected candidates enrolled in training or incubation program.',
    status: 'active',
    sourceUrl: 'https://ignite.gov.pk',
    sourceName: 'Ignite Official',
    verificationStatus: 'verified',
    courses: [
      { name: 'AI & Machine Learning Fundamentals', duration: '4 months', description: 'Python, TensorFlow, neural networks, computer vision, NLP basics', fee: 'Free', certification: 'Ignite AI Certificate', batchStart: 'Quarterly' },
      { name: 'Blockchain Development', duration: '3 months', description: 'Ethereum, smart contracts, DApps, Solidity programming', fee: 'Free', certification: 'Ignite Blockchain Certificate', batchStart: 'Quarterly' },
      { name: 'IoT & Embedded Systems', duration: '4 months', description: 'Arduino, Raspberry Pi, sensor integration, cloud connectivity', fee: 'Free', certification: 'Ignite IoT Certificate', batchStart: 'Quarterly' },
      { name: 'Cloud Computing & DevOps', duration: '3 months', description: 'AWS/Azure basics, Docker, Kubernetes, CI/CD pipelines', fee: 'Free', certification: 'Ignite Cloud Certificate', batchStart: 'Quarterly' },
    ],
    entryTests: [
      {
        testName: 'Ignite Technical Assessment',
        type: 'technical',
        totalMarks: 100,
        passingMarks: 60,
        passingPercentage: '60%',
        syllabus: 'Programming fundamentals (any language), data structures basics, logical reasoning, problem-solving, technology awareness',
        preparationTips: 'Practice programming on HackerRank/LeetCode. Study data structures (arrays, linked lists, trees). Review basic algorithms. Understand current tech trends. Ignite provides practice tests on website.',
      },
    ],
    documents: [
      { documentName: 'CNIC', description: 'Valid National Identity Card', isRequired: true },
      { documentName: 'Degree Certificate', description: 'Bachelor\'s degree or above (for advanced courses)', isRequired: true },
      { documentName: 'CV / Resume', description: 'Updated CV with technical skills highlighted', isRequired: true },
      { documentName: 'Portfolio', description: 'GitHub link or project portfolio (if available)', isRequired: false },
      { documentName: 'Motivation Letter', description: 'Brief statement of purpose', isRequired: true },
    ],
  },
  {
    name: 'PITB (Punjab Information Technology Board)',
    type: 'govt',
    description: 'Punjab government\'s IT initiative providing free technology training and certification programs. Focus on freelancing, software development, and digital skills. Training centers across Punjab.',
    website: 'https://pitb.gov.pk',
    location: 'Lahore (HQ), Training centers across Punjab',
    province: 'punjab',
    contactEmail: 'info@pitb.gov.pk',
    contactPhone: '+92-42-35813106',
    eligibilityCriteria: 'Age 18-40 years. Minimum Matriculation. Must be Punjab resident. Must be unemployed or earning below PKR 30,000/month. Priority to IT sector aspirants.',
    applicationProcess: 'Apply through PITB DigiSkills platform or partner institutes. Register for course. Appear for basic assessment. Selected candidates enrolled in training program. Training includes practical projects and job placement assistance.',
    status: 'active',
    sourceUrl: 'https://digiskills.pk',
    sourceName: 'PITB / DigiSkills',
    verificationStatus: 'verified',
    courses: [
      { name: 'Freelancing & Earning Online', duration: '12 weeks', description: 'Upwork, Fiverr, Freelancer, bidding, proposals, client management', fee: 'Free', certification: 'PITB DigiSkills Certificate', batchStart: 'Rolling enrollment' },
      { name: 'Graphic Design', duration: '12 weeks', description: 'Photoshop, Illustrator, Canva, logo design, branding', fee: 'Free', certification: 'PITB DigiSkills Certificate', batchStart: 'Rolling enrollment' },
      { name: 'SEO & Content Marketing', duration: '12 weeks', description: 'On-page SEO, keyword research, content writing, WordPress', fee: 'Free', certification: 'PITB DigiSkills Certificate', batchStart: 'Rolling enrollment' },
      { name: 'QuickBooks & Accounting', duration: '8 weeks', description: 'Financial accounting, invoicing, tax management, reports', fee: 'Free', certification: 'PITB DigiSkills Certificate', batchStart: 'Rolling enrollment' },
      { name: 'E-Commerce Management', duration: '12 weeks', description: 'Daraz seller, Shopify, inventory management, customer service', fee: 'Free', certification: 'PITB DigiSkills Certificate', batchStart: 'Rolling enrollment' },
      { name: 'WordPress Development', duration: '12 weeks', description: 'WordPress setup, theme customization, plugin development, hosting', fee: 'Free', certification: 'PITB DigiSkills Certificate', batchStart: 'Rolling enrollment' },
    ],
    entryTests: [
      {
        testName: 'DigiSkills Basic Assessment',
        type: 'aptitude',
        totalMarks: 50,
        passingMarks: 25,
        passingPercentage: '50%',
        syllabus: 'Basic computer knowledge, internet skills, English comprehension, general aptitude',
        preparationTips: 'Practice using internet and basic computer operations. Learn basic English. DigiSkills provides free pre-assessment on platform. No special preparation needed for most courses.',
      },
    ],
    documents: [
      { documentName: 'CNIC', description: 'Valid National Identity Card', isRequired: true },
      { documentName: 'Educational Certificates', description: 'Matric or above certificates', isRequired: true },
      { documentName: 'Domicile', description: 'Punjab domicile (preferred)', isRequired: false },
      { documentName: 'Photographs', description: '2 passport-size photographs', isRequired: true },
    ],
  },
  {
    name: 'TEVTA (Technical Education & Vocational Training Authority)',
    type: 'govt',
    description: 'Punjab government\'s technical education authority providing free vocational training. Offers courses in automotive, electrical, plumbing, IT, hospitality, and industrial trades. Training at government polytechnic institutes.',
    website: 'https://tevta.gop.pk',
    location: 'Lahore (HQ), TEVTA institutes across Punjab',
    province: 'punjab',
    contactEmail: 'info@tevta.gop.pk',
    contactPhone: '+92-42-37023000',
    eligibilityCriteria: 'Age 15-45 years. Minimum education: Middle (8th grade) for most courses, Matric for advanced courses. Must be Punjab resident. Must be unemployed or career changer.',
    applicationProcess: 'Visit nearest TEVTA institute. Register for preferred trade course. Appear for entry test (for some courses). Selected candidates enrolled in 3-18 month programs. All training provided free of cost.',
    status: 'active',
    sourceUrl: 'https://tevta.gop.pk',
    sourceName: 'TEVTA Official',
    verificationStatus: 'verified',
    courses: [
      { name: 'Automobile Mechanic', duration: '12 months', description: 'Engine repair, transmission, electrical systems, diagnostics', fee: 'Free', certification: 'TEVTA Trade Certificate', batchStart: 'January, July' },
      { name: 'Electrician', duration: '6 months', description: 'House wiring, motor winding, solar systems, safety', fee: 'Free', certification: 'TEVTA Trade Certificate', batchStart: 'January, July' },
      { name: 'Plumber', duration: '6 months', description: 'Residential plumbing, pipe fitting, water pumps, drainage', fee: 'Free', certification: 'TEVTA Trade Certificate', batchStart: 'January, July' },
      { name: 'Welder & Fabricator', duration: '6 months', description: 'Arc welding, gas welding, fabrication, metal work', fee: 'Free', certification: 'TEVTA Trade Certificate', batchStart: 'January, July' },
      { name: 'Tailoring & Dress Making', duration: '6 months', description: 'Cutting, stitching, embroidery, fashion design basics', fee: 'Free', certification: 'TEVTA Trade Certificate', batchStart: 'January, July' },
      { name: 'Computer Operator', duration: '6 months', description: 'MS Office, data entry, basic troubleshooting, internet', fee: 'Free', certification: 'TEVTA Trade Certificate', batchStart: 'January, July' },
    ],
    entryTests: [
      {
        testName: 'TEVTA Trade Aptitude Test',
        type: 'aptitude',
        totalMarks: 100,
        passingMarks: 40,
        passingPercentage: '40%',
        syllabus: 'General knowledge, basic mathematics, trade-specific questions, physical fitness (for some trades)',
        preparationTips: 'For IT courses: practice basic computer operations. For trade courses: basic math and mechanical aptitude. TEVTA provides practice materials at institutes.',
      },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document (15+ years old can use B-Form)', isRequired: true },
      { documentName: 'Educational Certificates', description: 'Middle/Matric certificates', isRequired: true },
      { documentName: 'Domicile', description: 'Punjab domicile', isRequired: false },
      { documentName: 'Photographs', description: '4 passport-size photographs', isRequired: true },
    ],
  },
  {
    name: 'HANDS (Health and Nutrition Development Society)',
    type: 'ngo',
    description: 'Major Pakistani NGO providing free healthcare training, nutrition education, and community development courses. Offers courses in community health, midwifery, nutrition, and public health.',
    website: 'https://hands.org.pk',
    location: 'Karachi (HQ), Branches in Sindh, Punjab, Balochistan',
    province: 'sindh',
    contactEmail: 'info@hands.org.pk',
    contactPhone: '+92-21-34542014',
    eligibilityCriteria: 'Age 18-40 years. Minimum Matriculation education. Must be Pakistani citizen. Priority to women for health/nutrition courses. Must be willing to work in rural/underserved communities.',
    applicationProcess: 'Apply at nearest HANDS center. Submit application with educational documents. Appear for interview. Selected candidates enrolled in training program. Training includes field work in rural areas.',
    status: 'active',
    sourceUrl: 'https://hands.org.pk',
    sourceName: 'HANDS Pakistan',
    verificationStatus: 'verified',
    courses: [
      { name: 'Community Health Worker Training', duration: '6 months', description: 'First aid, maternal health, child care, disease prevention, nutrition', fee: 'Free', certification: 'HANDS Community Health Certificate', batchStart: 'Quarterly' },
      { name: 'Lady Health Worker (LHW) Course', duration: '6 months', description: 'Family planning, antenatal care, immunization, health education', fee: 'Free', certification: 'HANDS LHW Certificate', batchStart: 'Quarterly' },
      { name: 'Nutrition & Dietetics', duration: '3 months', description: 'Malnutrition management, food preparation, community nutrition', fee: 'Free', certification: 'HANDS Nutrition Certificate', batchStart: 'Quarterly' },
      { name: 'Basic Life Support (BLS)', duration: '1 month', description: 'CPR, first aid, emergency response, basic medical care', fee: 'Free', certification: 'HANDS BLS Certificate', batchStart: 'Monthly' },
    ],
    entryTests: [
      {
        testName: 'HANDS Basic Assessment',
        type: 'aptitude',
        totalMarks: 50,
        passingMarks: 20,
        passingPercentage: '40%',
        syllabus: 'General knowledge, basic science, English comprehension, motivation assessment',
        preparationTips: 'Review basic science concepts (biology, health). Practice English comprehension. Understand community health basics. HANDS provides orientation before assessment.',
      },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document', isRequired: true },
      { documentName: 'Educational Certificates', description: 'Matric or above certificates', isRequired: true },
      { documentName: 'Photographs', description: '4 passport-size photographs', isRequired: true },
      { documentName: 'Character Certificate', description: 'From local imam/municipal officer (if available)', isRequired: false },
    ],
  },
  {
    name: 'Aga Khan Foundation (AKF) Skills Program',
    type: 'international',
    description: 'International NGO providing free vocational and life skills training in Pakistan. Focus on youth empowerment, women\'s education, and community development. Programs in remote areas of Sindh, Gilgit-Baltistan, and Chitral.',
    website: 'https://akdn.org',
    location: 'Karachi, Gilgit-Baltistan, Chitral, Chitral',
    province: 'all',
    contactEmail: 'info@akf.org.pk',
    contactPhone: '+92-21-35822255',
    eligibilityCriteria: 'Age 16-35 years. Minimum Middle education. Must be from AKF target areas (GB, Chitral, rural Sindh). Must be from low-income family. Priority to women and out-of-school youth.',
    applicationProcess: 'Apply through AKF field offices. Community-based selection process. Shortlisted candidates appear for group interview. Selected candidates enrolled in skills training program. Training includes stipend and materials.',
    status: 'active',
    sourceUrl: 'https://akdn.org/our-agencies/aga-khan-foundation',
    sourceName: 'Aga Khan Foundation',
    verificationStatus: 'verified',
    courses: [
      { name: 'Livestock & Dairy Management', duration: '3 months', description: 'Animal care, milk production, dairy business, feed management', fee: 'Free (with stipend)', certification: 'AKF Livestock Certificate', batchStart: 'Quarterly' },
      { name: 'Agriculture & Food Processing', duration: '3 months', description: 'Crop management, food preservation, organic farming, marketing', fee: 'Free (with stipend)', certification: 'AKF Agriculture Certificate', batchStart: 'Quarterly' },
      { name: 'Tourism & Hospitality', duration: '3 months', description: 'Hotel management, tour guiding, food service, customer care', fee: 'Free (with stipend)', certification: 'AKF Tourism Certificate', batchStart: 'Quarterly' },
      { name: 'Women\'s Empowerment Program', duration: '6 months', description: 'Financial literacy, small business management, communication skills', fee: 'Free (with stipend)', certification: 'AKF Empowerment Certificate', batchStart: 'Quarterly' },
    ],
    entryTests: [
      {
        testName: 'AKF Community Selection Assessment',
        type: 'interview',
        totalMarks: 100,
        passingMarks: 50,
        passingPercentage: '50%',
        syllabus: 'Personal interview, motivation assessment, basic literacy check, community needs discussion',
        preparationTips: 'Be prepared to discuss your motivation for joining. Understand your community\'s needs. Practice basic communication in local language. No formal written test for most programs.',
      },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document', isRequired: true },
      { documentName: 'Educational Certificates', description: 'Previous education certificates', isRequired: true },
      { documentName: 'Income Certificate', description: 'Family income proof or BISP registration', isRequired: true },
      { documentName: 'Photographs', description: '4 passport-size photographs', isRequired: true },
      { documentName: 'Community Reference', description: 'Reference from local community leader', isRequired: false },
    ],
  },
  {
    name: 'Daak Foundation (Digital Literacy Program)',
    type: 'ngo',
    description: 'Non-profit providing free digital literacy and IT training to underserved communities. Focus on basic computer skills, internet usage, and digital payment systems. Training centers in rural and semi-urban areas.',
    website: 'https://daakfoundation.org',
    location: 'Islamabad, Lahore, Multan, Peshawar',
    province: 'all',
    contactEmail: 'info@daakfoundation.org',
    contactPhone: '+92-51-2300000',
    eligibilityCriteria: 'Age 14-50 years. No minimum education requirement for basic courses. Must be from underserved community. Priority to women, persons with disabilities, and out-of-school youth.',
    applicationProcess: 'Visit nearest Daak center. Register for course. No entry test for basic courses. Advanced courses may require basic computer knowledge assessment. Training provided in local languages.',
    status: 'active',
    sourceUrl: 'https://daakfoundation.org',
    sourceName: 'Daak Foundation',
    verificationStatus: 'verified',
    courses: [
      { name: 'Basic Computer Literacy', duration: '1 month', description: 'MS Word, Excel, PowerPoint, internet browsing, email', fee: 'Free', certification: 'Daak Digital Literacy Certificate', batchStart: 'Monthly' },
      { name: 'Mobile Banking & Digital Payments', duration: '2 weeks', description: 'JazzCash, Easypaisa, online banking, digital safety', fee: 'Free', certification: 'Daak Digital Payments Certificate', batchStart: 'Monthly' },
      { name: 'Internet & Email Basics', duration: '2 weeks', description: 'Web browsing, search engines, email, social media safety', fee: 'Free', certification: 'Daak Internet Basics Certificate', batchStart: 'Monthly' },
      { name: 'Women\'s Digital Literacy', duration: '1 month', description: 'Tailored for women: basic computing, online safety, e-commerce', fee: 'Free', certification: 'Daak Women\'s Digital Certificate', batchStart: 'Monthly' },
    ],
    entryTests: [
      {
        testName: 'No Entry Test',
        type: 'none',
        totalMarks: null,
        passingMarks: null,
        passingPercentage: 'N/A',
        syllabus: 'No formal entry test. Basic literacy assessment may be conducted for advanced courses.',
        preparationTips: 'No preparation needed for basic courses. For advanced courses, basic computer knowledge is helpful.',
      },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document', isRequired: true },
      { documentName: 'Photographs', description: '2 passport-size photographs', isRequired: true },
    ],
  },
  {
    name: 'Robinson Crusoe (RC) Foundation',
    type: 'ngo',
    description: 'NGO providing free vocational training to street children and out-of-school youth. Focus on practical skills like tailoring, carpentry, beauty salon, and IT basics. Training provided with meals and accommodation.',
    website: 'https://rcfoundation.org.pk',
    location: 'Lahore, Karachi, Faisalabad',
    province: 'all',
    contactEmail: 'info@rcfoundation.org.pk',
    contactPhone: '+92-42-35780000',
    eligibilityCriteria: 'Age 12-25 years. Must be out-of-school youth or street child. No education requirement. Must be willing to attend regular classes. Priority to orphans and vulnerable children.',
    applicationProcess: 'Walk-in registration at RC center. Basic interview and needs assessment. Selected candidates enrolled immediately. Training includes meals, accommodation, and stipend.',
    status: 'active',
    sourceUrl: 'https://rcfoundation.org.pk',
    sourceName: 'RC Foundation',
    verificationStatus: 'verified',
    courses: [
      { name: 'Tailoring & Stitching', duration: '6 months', description: 'Machine stitching, cutting, embroidery, garment making', fee: 'Free (with meals and accommodation)', certification: 'RC Foundation Trade Certificate', batchStart: 'Rolling enrollment' },
      { name: 'Carpentry & Woodwork', duration: '6 months', description: 'Furniture making, wood carving, finishing, tool usage', fee: 'Free (with meals and accommodation)', certification: 'RC Foundation Trade Certificate', batchStart: 'Rolling enrollment' },
      { name: 'Beauty Salon & Cosmetology', duration: '6 months', description: 'Hair styling, makeup, skin care, salon management', fee: 'Free (with meals and accommodation)', certification: 'RC Foundation Beauty Certificate', batchStart: 'Rolling enrollment' },
      { name: 'Basic Computer Skills', duration: '3 months', description: 'MS Office, internet, email, typing, basic design', fee: 'Free (with meals and accommodation)', certification: 'RC Foundation IT Certificate', batchStart: 'Rolling enrollment' },
    ],
    entryTests: [
      {
        testName: 'RC Foundation Basic Assessment',
        type: 'interview',
        totalMarks: null,
        passingMarks: null,
        passingPercentage: 'N/A',
        syllabus: 'Personal interview, motivation assessment, basic literacy check',
        preparationTips: 'No formal preparation needed. RC Foundation focuses on motivation and willingness to learn.',
      },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document', isRequired: true },
      { documentName: 'Photographs', description: '4 passport-size photographs', isRequired: true },
    ],
  },
  {
    name: 'Karandaaz Pakistan (Digital Skills)',
    type: 'govt',
    description: 'Government-backed digital skills initiative providing free training in financial technology, digital payments, and e-commerce. Partners with private sector for industry-relevant training.',
    website: 'https://karandaaz.com',
    location: 'Islamabad, Lahore, Karachi',
    province: 'all',
    contactEmail: 'info@karandaaz.com',
    contactPhone: '+92-51-2300000',
    eligibilityCriteria: 'Age 18-35 years. Minimum Matriculation. Must be Pakistani citizen. Must be interested in fintech or digital payments sector. Basic computer literacy preferred.',
    applicationProcess: 'Apply through Karandaaz website. Submit application with CV. Appear for online assessment. Selected candidates enrolled in training program. Industry placement assistance provided.',
    status: 'active',
    sourceUrl: 'https://karandaaz.com',
    sourceName: 'Karandaaz Pakistan',
    verificationStatus: 'verified',
    courses: [
      { name: 'FinTech Fundamentals', duration: '3 months', description: 'Digital payments, mobile banking, blockchain basics, fintech landscape', fee: 'Free', certification: 'Karandaaz FinTech Certificate', batchStart: 'Quarterly' },
      { name: 'E-Commerce & Online Business', duration: '2 months', description: 'Online store setup, payment gateways, logistics, marketing', fee: 'Free', certification: 'Karandaaz E-Commerce Certificate', batchStart: 'Quarterly' },
      { name: 'Data Analytics for Business', duration: '3 months', description: 'Excel analytics, Google Analytics, business intelligence basics', fee: 'Free', certification: 'Karandaaz Analytics Certificate', batchStart: 'Quarterly' },
    ],
    entryTests: [
      {
        testName: 'Karandaaz Online Assessment',
        type: 'technical',
        totalMarks: 100,
        passingMarks: 50,
        passingPercentage: '50%',
        syllabus: 'Basic computer skills, internet knowledge, English comprehension, numerical reasoning',
        preparationTips: 'Practice basic computer operations and internet skills. Review English comprehension. Study basic business concepts. Karandaaz provides practice tests on website.',
      },
    ],
    documents: [
      { documentName: 'CNIC', description: 'Valid National Identity Card', isRequired: true },
      { documentName: 'Educational Certificates', description: 'Matric or above certificates', isRequired: true },
      { documentName: 'CV', description: 'Updated CV/resume', isRequired: true },
      { documentName: 'Photographs', description: '2 passport-size photographs', isRequired: true },
    ],
  },
  {
    name: 'Pakistani American Cultural Center (PACC) Skills',
    type: 'international',
    description: 'US-funded initiative providing free English language and IT skills training to Pakistani youth. Focus on improving English proficiency and digital skills for global employment opportunities.',
    website: 'https://usefpakistan.org',
    location: 'Lahore, Karachi, Islamabad',
    province: 'all',
    contactEmail: 'info@usefpakistan.org',
    contactPhone: '+92-42-35780000',
    eligibilityCriteria: 'Age 18-30 years. Minimum Intermediate education. Must be Pakistani citizen. Must have good academic record. English proficiency test may be required for advanced courses.',
    applicationProcess: 'Apply through USEF Pakistan website. Submit application with transcripts. Appear for English proficiency test (TOEFL/IELTS format). Shortlisted candidates enrolled in training program.',
    status: 'active',
    sourceUrl: 'https://usefpakistan.org',
    sourceName: 'USEF Pakistan',
    verificationStatus: 'verified',
    courses: [
      { name: 'Advanced English Communication', duration: '3 months', description: 'Academic writing, presentation skills, business English, IELTS prep', fee: 'Free', certification: 'PACC English Certificate', batchStart: 'Quarterly' },
      { name: 'Professional IT Skills', duration: '3 months', description: 'Advanced MS Office, data analysis, project management tools', fee: 'Free', certification: 'PACC IT Certificate', batchStart: 'Quarterly' },
    ],
    entryTests: [
      {
        testName: 'USEF English Proficiency Test',
        type: 'technical',
        totalMarks: 100,
        passingMarks: 60,
        passingPercentage: '60%',
        syllabus: 'Reading comprehension, grammar, vocabulary, writing skills, listening comprehension',
        preparationTips: 'Practice IELTS-style questions. Read English newspapers daily. Practice writing essays. Watch English news/podcasts. USEF provides free practice materials.',
      },
    ],
    documents: [
      { documentName: 'CNIC', description: 'Valid National Identity Card', isRequired: true },
      { documentName: 'Academic Transcripts', description: 'All previous academic transcripts', isRequired: true },
      { documentName: 'English Proficiency Score', description: 'IELTS/TOEFL score if available (not mandatory)', isRequired: false },
      { documentName: 'CV', description: 'Updated CV', isRequired: true },
      { documentName: 'Photographs', description: '4 passport-size photographs', isRequired: true },
    ],
  },
  {
    name: 'Pakistan Poverty Alleviation Fund (PPAF) Skills',
    type: 'govt',
    description: 'Government initiative providing free vocational training through partner NGOs. Covers agriculture, livestock, health, education, and enterprise development. Training provided in rural and underserved areas.',
    website: 'https://ppaf.org.pk',
    location: 'Islamabad (HQ), Field offices across Pakistan',
    province: 'all',
    contactEmail: 'info@ppaf.org.pk',
    contactPhone: '+92-51-2300000',
    eligibilityCriteria: 'Age 18-50 years. Minimum education: Middle. Must be from PPAF target communities. Priority to women, disabled persons, and marginalized communities.',
    applicationProcess: 'Apply through PPAF partner NGO in your area. Community-based selection process. Selected candidates enrolled in skills training. Training includes stipend, materials, and certification.',
    status: 'active',
    sourceUrl: 'https://ppaf.org.pk',
    sourceName: 'PPAF Official',
    verificationStatus: 'verified',
    courses: [
      { name: 'Agriculture & Crop Management', duration: '3 months', description: 'Modern farming techniques, irrigation, pest management, market linkages', fee: 'Free (with stipend)', certification: 'PPAF Agriculture Certificate', batchStart: 'Quarterly' },
      { name: 'Livestock Management', duration: '3 months', description: 'Animal care, breeding, milk production, dairy business', fee: 'Free (with stipend)', certification: 'PPAF Livestock Certificate', batchStart: 'Quarterly' },
      { name: 'Health & Sanitation', duration: '2 months', description: 'Basic health, hygiene, disease prevention, community health', fee: 'Free (with stipend)', certification: 'PPAF Health Certificate', batchStart: 'Quarterly' },
      { name: 'Micro-Enterprise Development', duration: '3 months', description: 'Business planning, financial management, marketing, compliance', fee: 'Free (with stipend)', certification: 'PPAF Enterprise Certificate', batchStart: 'Quarterly' },
    ],
    entryTests: [
      {
        testName: 'PPAF Community Assessment',
        type: 'interview',
        totalMarks: null,
        passingMarks: null,
        passingPercentage: 'N/A',
        syllabus: 'Personal interview, community needs assessment, motivation evaluation',
        preparationTips: 'Be prepared to discuss your community and how the training will help. No formal written test.',
      },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document', isRequired: true },
      { documentName: 'Community Certificate', description: 'Certificate from local community leader', isRequired: true },
      { documentName: 'Photographs', description: '4 passport-size photographs', isRequired: true },
    ],
  },
];

async function main() {
  console.log('Seeding free course institutions...');

  await prisma.institutionDocument.deleteMany();
  await prisma.institutionEntryTest.deleteMany();
  await prisma.institutionCourse.deleteMany();
  await prisma.freeInstitution.deleteMany();

  let count = 0;
  for (const inst of institutions) {
    const { courses, entryTests, documents, ...instData } = inst;
    const created = await prisma.freeInstitution.create({
      data: {
        ...instData,
        courses: {
          create: courses.map(c => ({
            name: c.name,
            duration: c.duration,
            description: c.description,
            fee: c.fee,
            certification: c.certification,
            batchStart: c.batchStart,
          })),
        },
        entryTests: {
          create: entryTests.map(t => ({
            testName: t.testName,
            type: t.type,
            totalMarks: t.totalMarks,
            passingMarks: t.passingMarks,
            passingPercentage: t.passingPercentage,
            syllabus: t.syllabus,
            preparationTips: t.preparationTips,
          })),
        },
        documents: {
          create: documents.map(d => ({
            documentName: d.documentName,
            description: d.description,
            isRequired: d.isRequired,
          })),
        },
      },
    });
    count++;
    console.log(`  ✅ ${count}. ${created.name}`);
  }

  console.log(`\nTotal institutions seeded: ${count}`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
