import { PrismaClient } from '@prisma/client';
const p = new PrismaClient();

const careers = [
  // ===== TECHNOLOGY =====
  { title: 'Software Engineer', slug: 'software-engineer', field: 'Computer Science', description: 'Design, develop, and maintain software applications. Work on everything from mobile apps to large-scale distributed systems.', skills: '["JavaScript","TypeScript","Python","Java","React","Node.js","SQL","Git","System Design","Problem Solving"]', entryRoles: '["Junior Software Engineer","Software Development Engineer (SDE I)","Frontend Developer","Backend Developer"]', certifications: '["AWS Certified Developer","Google Cloud Professional","Oracle Java Certified"]' },
  { title: 'AI/ML Engineer', slug: 'ai-ml-engineer', field: 'Computer Science', description: 'Build and deploy machine learning models and AI systems. Work on NLP, computer vision, recommendation systems, and generative AI.', skills: '["Python","TensorFlow","PyTorch","Deep Learning","Computer Vision","NLP","MLOps","Docker","Kubernetes","SQL"]', entryRoles: '["Junior ML Engineer","AI Research Assistant","ML Ops Engineer","Data Engineer (ML focus)"]', certifications: '["Google TensorFlow Developer","AWS Machine Learning Specialty","IBM AI Engineering"]' },
  { title: 'Data Scientist', slug: 'data-scientist', field: 'Data Science', description: 'Analyze complex data sets to extract insights and build predictive models. Combine statistics, programming, and domain knowledge.', skills: '["Python","R","SQL","Machine Learning","Statistics","Pandas","TensorFlow","Data Visualization","Jupyter","A/B Testing"]', entryRoles: '["Junior Data Scientist","Data Analyst","Machine Learning Engineer (Junior)","Business Intelligence Analyst"]', certifications: '["Google Data Analytics","IBM Data Science Professional","Microsoft Certified: Azure Data Scientist"]' },
  { title: 'Cybersecurity Analyst', slug: 'cybersecurity-analyst', field: 'Computer Science', description: 'Protect organizations from cyber threats. Monitor security systems, investigate breaches, and implement security measures.', skills: '["Network Security","Penetration Testing","SIEM","Linux","Python","Incident Response","Cryptography","Firewalls","Vulnerability Assessment"]', entryRoles: '["Security Analyst (Junior)","SOC Analyst (Tier 1)","IT Security Specialist","Vulnerability Analyst"]', certifications: '["CompTIA Security+","CEH (Certified Ethical Hacker)","CISSP","OSCP"]' },
  { title: 'Web Developer', slug: 'web-developer', field: 'Computer Science', description: 'Build and maintain websites and web applications. Work on frontend interfaces, backend APIs, and database systems.', skills: '["HTML","CSS","JavaScript","React","Vue.js","Node.js","REST APIs","GraphQL","Responsive Design","Git"]', entryRoles: '["Junior Web Developer","Frontend Developer","Full-Stack Developer (Junior)","UI Developer"]', certifications: '["freeCodeCamp Responsive Web Design","Meta Front-End Developer","AWS Certified Cloud Practitioner"]' },
  { title: 'Cloud Engineer', slug: 'cloud-engineer', field: 'Computer Science', description: 'Design, implement, and manage cloud infrastructure. Work with AWS, Azure, or GCP to deploy scalable applications.', skills: '["AWS","Azure","GCP","Terraform","Docker","Kubernetes","Linux","Networking","CI/CD","Python"]', entryRoles: '["Junior Cloud Engineer","Cloud Operations Analyst","DevOps Engineer (Junior)","Infrastructure Engineer"]', certifications: '["AWS Solutions Architect","Azure Administrator","Google Cloud Professional"]' },
  { title: 'Mobile App Developer', slug: 'mobile-app-developer', field: 'Computer Science', description: 'Build mobile applications for iOS and Android platforms. Work with React Native, Flutter, Swift, or Kotlin.', skills: '["React Native","Flutter","Swift","Kotlin","Firebase","REST APIs","UI/UX Design","Git","Testing"]', entryRoles: '["Junior Mobile Developer","iOS Developer","Android Developer","Cross-Platform Developer"]', certifications: '["Google Associate Android Developer","Apple Certified iOS Developer","Meta React Native Certificate"]' },
  { title: 'Database Administrator', slug: 'database-administrator', field: 'Computer Science', description: 'Manage and maintain database systems. Ensure data integrity, security, performance, and availability.', skills: '["SQL","MySQL","PostgreSQL","MongoDB","Database Design","Performance Tuning","Backup & Recovery","Security"]', entryRoles: '["Junior DBA","Database Analyst","Data Administrator","SQL Developer"]', certifications: '["Oracle Database Admin","Microsoft Certified: Azure Database","MongoDB Certified"]' },
  { title: 'DevOps Engineer', slug: 'devops-engineer', field: 'Computer Science', description: 'Bridge development and operations. Automate deployments, manage CI/CD pipelines, and ensure system reliability.', skills: '["Docker","Kubernetes","Jenkins","GitLab CI","Terraform","Ansible","Linux","Python","Monitoring","AWS"]', entryRoles: '["Junior DevOps Engineer","Build Engineer","Release Engineer","Infrastructure Engineer"]', certifications: '["AWS DevOps Professional","Kubernetes Administrator (CKA)","HashiCorp Terraform Associate"]' },
  { title: 'Product Manager (Tech)', slug: 'product-manager-tech', field: 'Computer Science', description: 'Lead product development from concept to launch. Define product vision, prioritize features, and work with engineering teams.', skills: '["Product Strategy","User Research","Data Analysis","Agile","Roadmapping","Stakeholder Management","SQL","A/B Testing"]', entryRoles: '["Associate Product Manager","Product Analyst","Technical Program Manager (Junior)"]', certifications: '["Pragmatic Institute","Scrum Product Owner","Google UX Design"]' },

  // ===== HEALTHCARE =====
  { title: 'Doctor (Physician)', slug: 'physician', field: 'Medicine', description: 'Diagnose and treat patients. Specialize in areas like cardiology, neurology, pediatrics, or surgery. Requires MBBS + specialization.', skills: '["Patient Diagnosis","Clinical Skills","Medical Knowledge","Communication","Empathy","Decision Making","Emergency Medicine"]', entryRoles: '["House Officer/Intern","Medical Officer","Resident (House Job)","General Practitioner"]', certifications: '["MBBS","PMDC Registration","Specialization (FCPS/MRCP/USMLE)"]' },
  { title: 'Nurse', slug: 'nurse', field: 'Medicine', description: 'Provide patient care, administer medications, and support doctors. Nursing is in high demand globally with excellent job prospects.', skills: '["Patient Care","Medication Administration","Vital Signs Monitoring","Communication","Empathy","Emergency Care","Documentation"]', entryRoles: '["Staff Nurse","Registered Nurse","ICU Nurse","Emergency Nurse"]', certifications: '["BSN (Bachelor of Science in Nursing)","RN License","Specialty Certifications"]' },
  { title: 'Pharmacist', slug: 'pharmacist', field: 'Medicine', description: 'Dispense medications, advise patients on drug interactions, and ensure safe pharmaceutical practices.', skills: '["Pharmacology","Patient Counseling","Drug Interactions"," dispensing","Inventory Management","Regulatory Compliance"]', entryRoles: '["Hospital Pharmacist","Community Pharmacist","Clinical Pharmacist (Junior)","Pharmaceutical Sales"]', certifications: '["Doctor of Pharmacy (PharmD)","Licensed Pharmacist","Board Certification"]' },
  { title: 'Medical Laboratory Technologist', slug: 'medical-lab-tech', field: 'Medicine', description: 'Perform laboratory tests on blood, tissue, and body fluids to help diagnose and treat diseases.', skills: '["Lab Techniques","Microscopy","Blood Banking","Quality Control","Safety Procedures","Equipment Operation"]', entryRoles: '["Lab Technician","Medical Lab Technologist","Pathology Assistant","Blood Bank Technologist"]', certifications: '["MLS (Medical Laboratory Scientist)","AMT Certification","Lab Tech License"]' },
  { title: 'Physical Therapist', slug: 'physical-therapist', field: 'Medicine', description: 'Help patients recover from injuries and improve mobility through exercise, massage, and other treatments.', skills: '["Rehabilitation","Manual Therapy","Exercise Prescription","Patient Assessment","Communication","Anatomy"]', entryRoles: '["Physical Therapist","Physical Therapy Assistant","Sports Rehab Specialist"]', certifications: '["DPT (Doctor of Physical Therapy)","Board Certification","Specialty Certifications"]' },
  { title: 'Public Health Specialist', slug: 'public-health-specialist', field: 'Medicine', description: 'Work on community health initiatives, disease prevention, and health policy. Focus on population health rather than individual patients.', skills: '["Epidemiology","Biostatistics","Health Policy","Program Management","Research","Community Health"]', entryRoles: '["Public Health Analyst","Epidemiologist (Junior)","Health Program Coordinator","Research Assistant"]', certifications: '["MPH (Master of Public Health)","CPH (Certified in Public Health)"]' },
  { title: 'Dentist', slug: 'dentist', field: 'Medicine', description: 'Diagnose and treat oral health issues. Perform procedures like fillings, extractions, and cosmetic dentistry.', skills: '["Oral Surgery","Prosthodontics","Orthodontics","Patient Care","Manual Dexterity","Diagnosis"]', entryRoles: '["General Dentist","Dental Surgeon","Orthodontist (after specialization)"]', certifications: '["BDS (Bachelor of Dental Surgery)","DDS/DMD","Specialty Board Certification"]' },
  { title: 'Medical Researcher', slug: 'medical-researcher', field: 'Medicine', description: 'Conduct research to advance medical knowledge. Work on new treatments, vaccines, and understanding diseases.', skills: '["Research Methodology","Statistics","Lab Techniques","Scientific Writing","Critical Thinking","Grant Writing"]', entryRoles: '["Research Assistant","Clinical Research Associate","Postdoctoral Researcher","Lab Manager"]', certifications: '["PhD in Biomedical Sciences","GCP Certification","IRB Training"]' },

  // ===== BUSINESS =====
  { title: 'Business Analyst', slug: 'business-analyst', field: 'Business', description: 'Analyze business processes and recommend improvements. Bridge between business stakeholders and technology teams.', skills: '["Requirements Gathering","Data Analysis","SQL","Excel","Stakeholder Management","Process Modeling","Communication"]', entryRoles: '["Junior Business Analyst","Business Systems Analyst","Data Analyst","Process Analyst"]', certifications: '["CBAP","PMI-PBA","Certified Scrum Product Owner"]' },
  { title: 'Financial Analyst', slug: 'financial-analyst', field: 'Business/Economics', description: 'Analyze financial data, create models, and provide investment recommendations. Work in banks, corporations, or consulting firms.', skills: '["Financial Modeling","Excel","SQL","Python","Accounting","Valuation","Bloomberg Terminal","Communication"]', entryRoles: '["Junior Financial Analyst","Investment Banking Analyst","Equity Research Analyst","Corporate Finance Analyst"]', certifications: '["CFA Level I","Financial Modeling (FMVA)","Bloomberg Market Concepts"]' },
  { title: 'Marketing Manager', slug: 'marketing-manager', field: 'Business', description: 'Develop and execute marketing strategies. Manage campaigns, analyze performance, and drive brand growth.', skills: '["Digital Marketing","SEO/SEM","Social Media","Analytics","Content Strategy","Brand Management","Communication","Creativity"]', entryRoles: '["Marketing Coordinator","Digital Marketing Specialist","Content Marketing Manager","Brand Manager (Junior)"]', certifications: '["Google Ads Certification","HubSpot Inbound Marketing","Meta Marketing Science"]' },
  { title: 'Management Consultant', slug: 'management-consultant', field: 'Business', description: 'Advise organizations on strategy, operations, and organizational challenges. Work on diverse projects across industries.', skills: '["Problem Solving","Data Analysis","Presentation","Excel","PowerPoint","Case Studies","Communication","Teamwork"]', entryRoles: '["Business Analyst (Consulting)","Associate Consultant","Strategy Analyst"]', certifications: '["MBA (preferred)","Lean Six Sigma","Prosci Change Management"]' },
  { title: 'Human Resources Manager', slug: 'hr-manager', field: 'Business', description: 'Manage recruitment, employee relations, training, and organizational development. Ensure compliance with labor laws.', skills: '["Recruitment","Employee Relations","Labor Law","Training","Conflict Resolution","HRIS Systems","Communication"]', entryRoles: '["HR Coordinator","Recruiter","Training Specialist","HR Generalist"]', certifications: '["SHRM-CP","PHR","CIPD"]' },
  { title: 'Supply Chain Manager', slug: 'supply-chain-manager', field: 'Business', description: 'Manage the flow of goods from suppliers to customers. Optimize logistics, procurement, and inventory management.', skills: '["Procurement","Logistics","Inventory Management","Data Analysis","ERP Systems","Negotiation","Forecasting"]', entryRoles: '["Supply Chain Analyst","Procurement Specialist","Logistics Coordinator","Operations Analyst"]', certifications: '["APICS CSCP","Six Sigma Green Belt","PMP"]' },
  { title: 'Entrepreneur', slug: 'entrepreneur', field: 'Business', description: 'Start and grow your own business. Identify opportunities, build products, raise funding, and lead teams.', skills: '["Leadership","Business Planning","Financial Management","Marketing","Sales","Networking","Risk Taking","Problem Solving"]', entryRoles: '["Founder","Co-Founder","Startup Associate","Business Development"]', certifications: '["Startup accelerators (Y Combinator, Techstars)","MBA","Lean Startup Certification"]' },
  { title: 'Accountant', slug: 'accountant', field: 'Business', description: 'Prepare and examine financial records. Ensure accuracy and compliance with tax laws and regulations.', skills: '["Accounting","Excel","Tax Preparation","GAAP/IFRS","Auditing","Financial Reporting","QuickBooks"]', entryRoles: '["Junior Accountant","Staff Auditor","Tax Associate","Bookkeeper"]', certifications: '["CPA (Certified Public Accountant)","ACCA","CMA"]' },

  // ===== ENGINEERING =====
  { title: 'Civil Engineer', slug: 'civil-engineer', field: 'Civil Engineering', description: 'Design and oversee construction of infrastructure projects like bridges, roads, buildings, and water systems.', skills: '["AutoCAD","Structural Analysis","Project Management","Construction","MATLAB","Site Supervision","Building Codes"]', entryRoles: '["Junior Civil Engineer","Site Engineer","Structural Engineer (Junior)","Construction Supervisor"]', certifications: '["PE (Professional Engineer)","PMP","LEED AP"]' },
  { title: 'Electrical Engineer', slug: 'electrical-engineer', field: 'Electrical Engineering', description: 'Design, develop, and test electrical systems and equipment. Work on power systems, electronics, and control systems.', skills: '["Circuit Design","Power Systems","MATLAB","Embedded Systems","PCB Design","Renewable Energy","Control Systems"]', entryRoles: '["Junior Electrical Engineer","Power Systems Engineer","Electronics Engineer","Control Systems Engineer"]', certifications: '["PE (Professional Engineer)","IEEE Certifications","Six Sigma"]' },
  { title: 'Mechanical Engineer', slug: 'mechanical-engineer', field: 'Mechanical Engineering', description: 'Design and manufacture mechanical systems. Work on engines, machines, HVAC systems, and manufacturing processes.', skills: '["CAD (SolidWorks/AutoCAD)","Thermodynamics","Fluid Mechanics","Manufacturing","FEA Analysis","3D Printing","Project Management"]', entryRoles: '["Junior Mechanical Engineer","Design Engineer","Manufacturing Engineer","Quality Engineer"]', certifications: '["PE (Professional Engineer)","Six Sigma Green Belt","CSWP (SolidWorks)"]' },
  { title: 'Chemical Engineer', slug: 'chemical-engineer', field: 'Engineering', description: 'Design processes for manufacturing chemicals, pharmaceuticals, and fuels. Work on process optimization and safety.', skills: '["Process Design","Chemical Engineering","MATLAB","Safety Management","Quality Control","Environmental Compliance"]', entryRoles: '["Junior Chemical Engineer","Process Engineer","Plant Engineer","Research Chemist"]', certifications: '["PE (Professional Engineer)","Six Sigma","Process Safety Management"]' },
  { title: 'Aerospace Engineer', slug: 'aerospace-engineer', field: 'Engineering', description: 'Design aircraft, spacecraft, satellites, and missiles. Work on aerodynamics, propulsion, and structural design.', skills: '["Aerodynamics","Propulsion","CAD","MATLAB","Flight Mechanics","Structural Analysis","Composite Materials"]', entryRoles: '["Junior Aerospace Engineer","Aerodynamics Engineer","Propulsion Engineer","Avionics Engineer"]', certifications: '["PE (Professional Engineer)","FAA Certifications","INCOSE Systems Engineering"]' },
  { title: 'Software Engineer (CSE)', slug: 'software-engineer-cse', field: 'Computer Science', description: 'Apply engineering principles to software development. Design scalable systems and lead technical teams.', skills: '["System Design","Algorithms","Data Structures","Cloud Computing","Microservices","DevOps","Leadership"]', entryRoles: '["Software Engineer","Senior Software Engineer","Tech Lead","Engineering Manager"]', certifications: '["AWS Solutions Architect","Google Cloud Professional","Azure Solutions Architect"]' },
  { title: 'Environmental Engineer', slug: 'environmental-engineer', field: 'Engineering', description: 'Develop solutions to environmental problems. Work on water treatment, waste management, and pollution control.', skills: '["Environmental Science","Water Treatment","Air Quality","Waste Management","GIS","Regulatory Compliance"]', entryRoles: '["Junior Environmental Engineer","Environmental Consultant","Sustainability Analyst"]', certifications: '["PE (Professional Engineer)","LEED AP","CHMM (Certified Hazardous Materials Manager)"]' },
  { title: 'Biomedical Engineer', slug: 'biomedical-engineer', field: 'Engineering', description: 'Combine engineering with medical science to design healthcare equipment, prosthetics, and medical devices.', skills: '["Biomechanics","Medical Devices","CAD","MATLAB","Tissue Engineering","Signal Processing","Regulatory Affairs"]', entryRoles: '["Junior Biomedical Engineer","Clinical Engineer","Medical Device Designer","Quality Engineer"]', certifications: '["PE (Professional Engineer)","CQE (Certified Quality Engineer)","Six Sigma"]' },

  // ===== ARTS =====
  { title: 'Graphic Designer', slug: 'graphic-designer', field: 'Design', description: 'Create visual content for print and digital media. Design logos, branding, advertisements, and user interfaces.', skills: '["Adobe Photoshop","Illustrator","InDesign","Typography","Color Theory","Layout Design","Brand Identity"]', entryRoles: '["Junior Graphic Designer","Visual Designer","Brand Designer","Production Artist"]', certifications: '["Adobe Certified Professional","Google UX Design","Canva Design School"]' },
  { title: 'Content Writer', slug: 'content-writer', field: 'Journalism', description: 'Create written content for websites, blogs, social media, and marketing. Specialize in specific niches like tech, health, or finance.', skills: '["Writing","SEO","Content Strategy","Research","WordPress","Social Media","Editing","Copywriting"]', entryRoles: '["Junior Content Writer","Blog Writer","Copywriter","Technical Writer"]', certifications: '["HubSpot Content Marketing","Google Analytics","Copywriting Certifications"]' },
  { title: 'Video Editor', slug: 'video-editor', field: 'Media', description: 'Edit and assemble raw footage into polished videos. Work on films, YouTube content, ads, and corporate videos.', skills: '["Adobe Premiere Pro","After Effects","DaVinci Resolve","Storytelling","Color Grading","Sound Design","Motion Graphics"]', entryRoles: '["Junior Video Editor","Assistant Editor","YouTube Editor","Production Assistant"]', certifications: '["Adobe Premiere Pro Certified","DaVinci Resolve Certified"]' },
  { title: 'Photographer', slug: 'photographer', field: 'Fine Arts', description: 'Capture images for commercial, editorial, or artistic purposes. Specialize in portraits, events, products, or photojournalism.', skills: '["Camera Operation","Lighting","Photoshop","Composition","Photo Editing","Business Skills","Communication"]', entryRoles: '["Freelance Photographer","Studio Assistant","Photojournalist","Commercial Photographer"]', certifications: '["Adobe Certified Professional","Photography Certifications"]' },
  { title: 'UX/UI Designer', slug: 'ux-ui-designer', field: 'Design', description: 'Design user interfaces and experiences for apps and websites. Combine aesthetics with usability research.', skills: '["Figma","Sketch","Adobe XD","User Research","Wireframing","Prototyping","Accessibility","Design Systems"]', entryRoles: '["Junior UX Designer","UI Designer","Interaction Designer","UX Researcher"]', certifications: '["Google UX Design","Nielsen Norman UX Certification","Interaction Design Foundation"]' },
  { title: 'Animator', slug: 'animator', field: 'Fine Arts', description: 'Create animations for films, games, advertisements, and social media. Work in 2D or 3D animation.', skills: '["Maya","Blender","After Effects","Character Design","Storyboarding","3D Modeling","Rigging"]', entryRoles: '["Junior Animator","Storyboard Artist","3D Modeler","Motion Graphics Designer"]', certifications: '["Autodesk Maya Certified","Blender Foundation Certified"]' },
  { title: 'Journalist', slug: 'journalist', field: 'Journalism', description: 'Research and report news stories. Work in print, broadcast, or digital media. Investigate and inform the public.', skills: '["Investigative Research","Writing","Interviewing","Media Ethics","Social Media","Video Production","Deadline Management"]', entryRoles: '["Reporter","News Correspondent","Digital Journalist","Freelance Writer"]', certifications: '["Journalism Degree","Investigative Reporters and Editors (IRE) Training"]' },
  { title: 'Social Media Manager', slug: 'social-media-manager', field: 'Marketing', description: 'Manage brand presence across social media platforms. Create content, engage audiences, and analyze performance.', skills: '["Social Media Strategy","Content Creation","Analytics","Community Management","Paid Advertising","Copywriting","Visual Design"]', entryRoles: '["Social Media Coordinator","Content Creator","Community Manager","Digital Marketing Specialist"]', certifications: '["Meta Social Media Marketing","Hootsuite Social Marketing","Google Digital Marketing"]' },

  // ===== EDUCATION =====
  { title: 'School Teacher', slug: 'school-teacher', field: 'Education', description: 'Teach students at primary or secondary level. Develop lesson plans, assess student progress, and create engaging learning environments.', skills: '["Classroom Management","Lesson Planning","Student Assessment","Communication","Patience","Curriculum Design","Technology Integration"]', entryRoles: '["Student Teacher","Teaching Assistant","Substitute Teacher","Classroom Teacher"]', certifications: '["Teaching License/Certification","B.Ed/M.Ed","Special Education Training"]' },
  { title: 'University Professor', slug: 'university-professor', field: 'Education', description: 'Teach at university level and conduct research. Publish papers, supervise students, and contribute to academic knowledge.', skills: '["Research","Teaching","Academic Writing","Grant Writing","Mentoring","Public Speaking","Critical Thinking"]', entryRoles: '["Lecturer","Assistant Professor","Postdoctoral Fellow","Research Associate"]', certifications: '["PhD in relevant field","NET/SET (India)","Teaching certifications"]' },
  { title: 'Education Administrator', slug: 'education-administrator', field: 'Education', description: 'Manage schools, colleges, or educational institutions. Handle operations, staffing, budgets, and educational policy.', skills: '["Leadership","Budget Management","Policy Development","Staff Management","Strategic Planning","Communication","Regulatory Compliance"]', entryRoles: '["Assistant Principal","Department Head","Academic Coordinator","Dean of Students"]', certifications: '["M.Ed in Educational Leadership","Principal Certification","PMP"]' },
  { title: 'Corporate Trainer', slug: 'corporate-trainer', field: 'Education', description: 'Design and deliver training programs for employees. Focus on skills development, compliance, and organizational learning.', skills: '["Instructional Design","Presentation","Learning Management Systems","Needs Assessment","Facilitation","Evaluation"]', entryRoles: '["Training Coordinator","Learning & Development Specialist","Instructional Designer"]', certifications: '["ATD Certification","CPTD (Certified Professional in Talent Development)","Train the Trainer"]' },
  { title: 'Online Course Creator', slug: 'online-course-creator', field: 'Education', description: 'Create and sell educational content on platforms like Udemy, Coursera, or YouTube. Build passive income through teaching.', skills: '["Course Design","Video Production","Subject Matter Expertise","Marketing","Platform Management","Student Engagement"]', entryRoles: '["Course Creator","Educational Content Producer","YouTube Educator","E-Learning Developer"]', certifications: '["Instructional Design Certificate","Video Production Course","Digital Marketing"]' },
  { title: 'Special Education Teacher', slug: 'special-education-teacher', field: 'Education', description: 'Work with students who have learning disabilities, emotional challenges, or physical impairments. Adapt teaching methods to individual needs.', skills: '["Special Education Methods","IEP Development","Behavioral Management","Patience","Adaptability","Communication","Assessment"]', entryRoles: '["Special Education Teacher","Resource Room Teacher","Inclusion Specialist"]', certifications: '["Special Education Certification","Board Certified Behavior Analyst (BCBA)","Assistive Technology Training"]' },
  { title: 'School Counselor', slug: 'school-counselor', field: 'Education', description: 'Support students with academic, career, and personal/social development. Provide guidance counseling and intervention services.', skills: '["Counseling","Active Listening","Career Guidance","Crisis Intervention","Group Facilitation","Assessment","Empathy"]', entryRoles: '["School Counselor","Career Counselor","Student Affairs Coordinator"]', certifications: '["Licensed Professional Counselor (LPC)","National Certified Counselor (NCC)","School Counseling Certification"]' },

  // ===== LAW =====
  { title: 'Lawyer', slug: 'lawyer', field: 'Law', description: 'Represent clients in legal matters. Specialize in areas like corporate law, criminal law, family law, or intellectual property.', skills: '["Legal Research","Litigation","Contract Drafting","Negotiation","Critical Thinking","Communication","Courtroom Skills"]', entryRoles: '["Junior Associate","Legal Analyst","Paralegal (before bar)","Public Defender"]', certifications: '["Bar Exam Pass","LLB/JD Degree","Specialization Certifications"]' },
  { title: 'Judge', slug: 'judge', field: 'Law', description: 'Preside over court proceedings and make legal judgments. Requires extensive legal experience and judicial appointment.', skills: '["Legal Knowledge","Decision Making","Impartiality","Court Management","Legal Writing","Ethics"]', entryRoles: '["Magistrate","District Judge","Sessions Judge","Supreme Court Judge"]', certifications: '["LLB/LLM","Judicial Service Exam","Years of Legal Practice"]' },
  { title: 'Legal Consultant', slug: 'legal-consultant', field: 'Law', description: 'Provide expert legal advice to organizations and individuals. Specialize in compliance, contracts, and regulatory matters.', skills: '["Legal Advisory","Compliance","Contract Review","Risk Assessment","Regulatory Analysis","Research"]', entryRoles: '["Legal Consultant","Compliance Officer","Corporate Counsel (Junior)","Legal Analyst"]', certifications: '["LLB/LLM","Specialized Certifications (IP, Tax, etc.)"]' },
  { title: 'Paralegal', slug: 'paralegal', field: 'Law', description: 'Assist lawyers with research, document preparation, and case management. A stepping stone to becoming a lawyer.', skills: '["Legal Research","Document Preparation","Case Management","Communication","Organization","Legal Software"]', entryRoles: '["Paralegal","Legal Assistant","Litigation Support","Document Review Specialist"]', certifications: '["Paralegal Certificate","Certified Paralegal (CP)","Legal Process Certification"]' },
  { title: 'Corporate Lawyer', slug: 'corporate-lawyer', field: 'Law', description: 'Handle legal matters for businesses including mergers, acquisitions, contracts, and corporate governance.', skills: '["M&A","Contract Law","Corporate Governance","Due Diligence","Negotiation","Securities Law","Drafting"]', entryRoles: '["Junior Associate (Corporate)","M&A Analyst","Legal Counsel (Junior)","Company Secretary"]', certifications: '["LLB/JD","Bar Admission","CS (Company Secretary)","Specialized M&A training"]' },

  // ===== SCIENCE =====
  { title: 'Research Scientist', slug: 'research-scientist', field: 'Physics', description: 'Conduct original research in physics, chemistry, or biology. Publish findings and advance scientific knowledge.', skills: '["Research Methodology","Laboratory Skills","Data Analysis","Scientific Writing","Statistics","Critical Thinking"]', entryRoles: '["Research Assistant","Lab Technician","Postdoctoral Researcher","Research Scientist"]', certifications: '["PhD in relevant field","Lab Safety Certifications","Grant Writing"]' },
  { title: 'Biologist', slug: 'biologist', field: 'Biology', description: 'Study living organisms and their environments. Work in research, conservation, healthcare, or biotechnology.', skills: '["Microscopy","Genetics","Molecular Biology","Field Research","Data Analysis","Laboratory Techniques"]', entryRoles: '["Lab Assistant","Research Associate","Field Biologist","Biotech Associate"]', certifications: '["MS in Biology","ASCP Certification (Clinical)","Biotech Certifications"]' },
  { title: 'Chemist', slug: 'chemist', field: 'Chemistry', description: 'Study the composition and properties of matter. Develop new materials, drugs, and chemical processes.', skills: '["Analytical Chemistry","Organic Chemistry","Lab Techniques","Spectroscopy","Chromatography","Safety"]', entryRoles: '["Lab Chemist","Quality Control Chemist","Research Chemist","Process Chemist"]', certifications: '["ACS Certified Degree","Analytical Chemistry Certification","Green Chemistry"]' },
  { title: 'Mathematician', slug: 'mathematician', field: 'Mathematics', description: 'Apply mathematical theories to solve real-world problems. Work in academia, finance, technology, or government.', skills: '["Advanced Mathematics","Statistics","Programming (Python/R)","Problem Solving","Modeling","Research"]', entryRoles: '["Mathematician","Actuary","Data Analyst","Operations Research Analyst"]', certifications: '["PhD in Mathematics","Actuarial Exams (SOA/CAS)","SAS Certification"]' },
  { title: 'Environmental Scientist', slug: 'environmental-scientist', field: 'Environmental Science', description: 'Study and address environmental issues like pollution, climate change, and conservation.', skills: '["Environmental Monitoring","GIS","Data Analysis","Regulatory Knowledge","Field Research","Sustainability"]', entryRoles: '["Environmental Analyst","Conservation Scientist","Sustainability Consultant","Climate Researcher"]', certifications: '["Environmental Science Degree","LEED AP","CHMM","REP (Registered Environmental Professional)"]' },
  { title: 'Psychologist', slug: 'psychologist', field: 'Psychology', description: 'Study human behavior and mental processes. Provide therapy, conduct research, or work in organizational settings.', skills: '["Clinical Assessment","Therapy","Research Methods","Statistics","Empathy","Communication","Ethics"]', entryRoles: '["Clinical Psychologist","Counselor","School Psychologist","Organizational Psychologist"]', certifications: '["Licensed Clinical Psychologist","RPsych","Board Certification in Psychology"]' },
  { title: 'Statistician', slug: 'statistician', field: 'Mathematics', description: 'Collect and analyze data to solve real problems. Work in government, healthcare, business, or research institutions.', skills: '["Statistical Analysis","R/Python","SAS","Survey Design","Machine Learning","Data Visualization"]', entryRoles: '["Junior Statistician","Biostatistician","Data Analyst","Survey Methodologist"]', certifications: '["ASA (American Statistical Association)","PStat (Professional Statistician)","SAS Certified"]' },

  // ===== GENERAL / CROSS-FIELD =====
  { title: 'Project Manager', slug: 'project-manager', field: 'General', description: 'Plan, execute, and close projects. Manage teams, budgets, and timelines across any industry.', skills: '["Project Planning","Risk Management","Budget Management","Communication","Leadership","Agile/Scrum","Stakeholder Management"]', entryRoles: '["Project Coordinator","Assistant Project Manager","Scrum Master","Program Assistant"]', certifications: '["PMP","PRINCE2","Certified ScrumMaster","Google Project Management"]' },
  { title: 'Management Consultant', slug: 'management-consultant-general', field: 'General', description: 'Solve complex business problems for organizations across industries. Analyze data, develop strategies, and implement solutions.', skills: '["Problem Solving","Data Analysis","Presentation","Excel","PowerPoint","Strategic Thinking","Communication"]', entryRoles: '["Analyst","Associate Consultant","Strategy Consultant (Junior)"]', certifications: '["MBA","Lean Six Sigma","Tableau/Power BI"]' },
  { title: 'Technical Writer', slug: 'technical-writer', field: 'General', description: 'Create documentation for software, hardware, and technical products. Make complex information accessible to users.', skills: '["Technical Writing","Documentation","API Documentation","Markdown","Information Design","Editing","HTML/CSS"]', entryRoles: '["Junior Technical Writer","Documentation Specialist","Knowledge Base Writer"]', certifications: '["STC Certification","API Documentation Training","Markdown/AsciiDoc"]' },
  { title: 'UX Researcher', slug: 'ux-researcher', field: 'Design', description: 'Conduct research to understand user needs and behaviors. Use findings to inform product design and strategy.', skills: '["User Research","Usability Testing","Interviews","Surveys","Data Analysis","Empathy","Report Writing"]', entryRoles: '["Junior UX Researcher","User Research Assistant","Product Analyst"]', certifications: '["Google UX Design","Nielsen Norman UX Certification","Human-Computer Interaction"]' },
];

(async () => {
  console.log(`Seeding ${careers.length} career paths...`);
  let count = 0;
  for (const c of careers) {
    try {
      await p.careerPath.upsert({
        where: { slug: c.slug },
        update: c,
        create: c,
      });
      count++;
    } catch (e) {
      console.error(`Failed: ${c.slug}`, e);
    }
  }
  console.log(`  ${count} career paths seeded`);

  // Summary
  const fields = await p.careerPath.groupBy({ by: ['field'], _count: true });
  console.log('\n=== Career Paths by Field ===');
  for (const f of fields.sort((a, b) => b._count - a._count)) {
    console.log(`  ${f.field}: ${f._count}`);
  }
  const total = await p.careerPath.count();
  console.log(`\nTotal: ${total} career paths`);

  await p.$disconnect();
})();
